package joshie.harvest.npcs;

import joshie.harvest.api.npc.NPCEntity;
import joshie.harvest.api.npc.schedule.ScheduleBuilder;
import joshie.harvest.api.npc.schedule.ScheduleBuilder.Conditional;
import joshie.harvest.calendar.HFFestivals;
import joshie.harvest.core.util.annotations.HFLoader;
import joshie.harvest.quests.town.festivals.QuestStarryNight;
import joshie.harvest.town.TownHelper;
import joshie.harvest.town.data.TownData;
import net.minecraft.world.World;

import javax.annotation.Nonnull;

import static joshie.harvest.api.calendar.Season.SPRING;
import static joshie.harvest.api.calendar.Weekday.*;
import static joshie.harvest.calendar.HFFestivals.*;
import static joshie.harvest.core.lib.LoadOrder.HFSCHEDULES;
import static joshie.harvest.npcs.HFNPCs.*;
import static joshie.harvest.town.BuildingLocations.*;

@HFLoader(priority = HFSCHEDULES)
@SuppressWarnings("unused")
public class HFSchedules {
    public static void init() {
        //If invited to the starry night festival, then go to the park
        Conditional isInvited = new Conditional() {
            @Override
            public boolean canDo(@Nonnull World world, @Nonnull NPCEntity npc) {
                TownData data = TownHelper.getClosestTownToEntity(npc.getAsEntity(), false);
                if (data.getFestival() == HFFestivals.STARRY_NIGHT) {
                    QuestStarryNight quest = data.getQuests().getAQuest(data.getFestival().getQuest());
                    return quest != null && quest.isInvited(npc);
                }

                return false;
            }
        };

        ScheduleBuilder.create(GODDESS, null).build();
        ScheduleBuilder.create(MINER, null).build();

        ScheduleBuilder.create(CARPENTER, CARPENTER_DOWNSTAIRS)
                .add(SPRING, SUNDAY, 0L, CARPENTER_DOWNSTAIRS)
                .add(SPRING, SUNDAY, 8000L, CARPENTER_FRONT)
                .add(SPRING, SUNDAY, 9000L, CARPENTER_WORK)
                .add(SPRING, SUNDAY, 17000L, CARPENTER_DOWNSTAIRS)
                .add(SPRING, SUNDAY, 21000L, CARPENTER_FRONT)
                .add(COOKING_CONTEST, 0L, CARPENTER_UPSTAIRS)
                .add(COOKING_CONTEST, 9000L, PARK_BENCH)
                .add(COOKING_CONTEST, 20000L, CARPENTER_UPSTAIRS)
                .add(NEW_YEARS, 0L, CARPENTER_DOWNSTAIRS)
                .add(NEW_YEARS, 10000L, CARPENTER_FRONT)
                .add(NEW_YEARS, 11500L, PARK_TRADER)
                .add(NEW_YEARS, 22500L, CARPENTER_DOWNSTAIRS)
                .add(COW_FESTIVAL, 0L, CARPENTER_DOWNSTAIRS)
                .add(COW_FESTIVAL, 6000L, PARK_BOTTOM)
                .add(COW_FESTIVAL, 18000L, CARPENTER_DOWNSTAIRS)
                .add(SHEEP_FESTIVAL, 0L, CARPENTER_DOWNSTAIRS)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_YULIF)
                .add(SHEEP_FESTIVAL, 18000L, CARPENTER_DOWNSTAIRS)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT1)
                .add(STARRY_NIGHT, 6000L, CARPENTER_FRONT)
                .add(STARRY_NIGHT, 9000L, CARPENTER_WORK)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT1)
                .add(PARK_STARRY_NIGHT_SEAT1, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_NOODLES_STAND)
                .add(NEW_YEARS_EVE, 6000L, CARPENTER_DOWNSTAIRS)
                .add(NEW_YEARS_EVE, 13000L, CARPENTER_FRONT)
                .add(NEW_YEARS_EVE, 17000L, PARK_NOODLES_STAND)
                .build();

        ScheduleBuilder.create(FLOWER_GIRL, CARPENTER_UPSTAIRS)
                .add(SPRING, SUNDAY, 0L, CARPENTER_UPSTAIRS)
                .add(SPRING, SUNDAY, 6000L, TOWNHALL_TEEN)
                .add(SPRING, SUNDAY, 8000L, CARPENTER_UPSTAIRS)
                .add(SPRING, SUNDAY, 17000L, PARK_BACK_LEFT)
                .add(SPRING, SUNDAY, 19000L, CARPENTER_FRONT)
                .add(SPRING, SUNDAY, 21000L, CARPENTER_UPSTAIRS)
                .add(COOKING_CONTEST, 0L, CARPENTER_UPSTAIRS)
                .add(COOKING_CONTEST, 6000L, PARK_CENTRE)
                .add(COOKING_CONTEST, 17000L, CARPENTER_UPSTAIRS)
                .add(NEW_YEARS, 0L, CARPENTER_UPSTAIRS)
                .add(NEW_YEARS, 10000L, CARPENTER_DOWNSTAIRS)
                .add(NEW_YEARS, 11500L, PARK_TRADER_LEFT)
                .add(NEW_YEARS, 22500L, CARPENTER_DOWNSTAIRS)
                .add(NEW_YEARS, 23500L, CARPENTER_UPSTAIRS)
                .add(COW_FESTIVAL, 0L, CARPENTER_UPSTAIRS)
                .add(COW_FESTIVAL, 6000L, PARK_BOTTOM)
                .add(COW_FESTIVAL, 18000L, CARPENTER_UPSTAIRS)
                .add(SHEEP_FESTIVAL, 0L, CARPENTER_UPSTAIRS)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_YULIF)
                .add(SHEEP_FESTIVAL, 18000L, CARPENTER_UPSTAIRS)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT2)
                .add(STARRY_NIGHT, 6000L, TOWNHALL_TEEN)
                .add(STARRY_NIGHT, 8000L, CARPENTER_UPSTAIRS)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT2)
                .add(PARK_STARRY_NIGHT_SEAT2, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_STAGE_LEFT)
                .add(NEW_YEARS_EVE, 6000L, CARPENTER_UPSTAIRS)
                .add(NEW_YEARS_EVE, 13000L, CARPENTER_DOWNSTAIRS)
                .add(NEW_YEARS_EVE, 17000L, PARK_STAGE_LEFT)
                .build();

        ScheduleBuilder.create(GS_OWNER, GENERAL_BEDROOM)
                .add(SPRING, SUNDAY, 0L, GENERAL_BEDROOM)
                .add(SPRING, SUNDAY, 8000L, GENERAL_BEDROOM)
                .add(SPRING, SUNDAY, 10000L, PARK_CENTRE)
                .add(SPRING, SUNDAY, 15000L, CAFE_FRONT)
                .add(SPRING, SUNDAY, 17000L, GENERAL_STORE_FRONT)
                .add(SPRING, SUNDAY, 19000L, CAFE_KITCHEN)
                .add(SPRING, SUNDAY, 22000L, GENERAL_BED)
                .add(SPRING, MONDAY, 0L, GENERAL_BEDROOM)
                .add(SPRING, MONDAY, 7500L, GENERAL_TILL)
                .add(SPRING, MONDAY, 17000L, GENERAL_BEDROOM)
                .add(SPRING, MONDAY, 22000L, FISHING_POND_BACK)
                .add(SPRING, SATURDAY, 0L, GENERAL_BEDROOM)
                .add(SPRING, SATURDAY, 10000L, GENERAL_TILL)
                .add(SPRING, SATURDAY, 16000L, CAFE_CUSTOMER)
                .add(SPRING, SATURDAY, 19000L, CAFE_KITCHEN)
                .add(SPRING, SATURDAY, 22000L, FISHING_POND_BACK)
                .add(COOKING_CONTEST, 0L, GENERAL_BEDROOM)
                .add(COOKING_CONTEST, 4500L, PARK_PODIUM)
                .add(COOKING_CONTEST, 18000L, GENERAL_BEDROOM)
                .add(COOKING_CONTEST, 20000L, FISHING_POND_BACK)
                .add(NEW_YEARS, 0L, GENERAL_BEDROOM)
                .add(NEW_YEARS, 7000L, GENERAL_GARDEN)
                .add(NEW_YEARS, 12000L, PARK_OAK)
                .add(NEW_YEARS, 20000L, GENERAL_GARDEN)
                .add(NEW_YEARS, 22000L, GENERAL_BEDROOM)
                .add(COW_FESTIVAL, 0L, GENERAL_BEDROOM)
                .add(COW_FESTIVAL, 6000L, PARK_COW_BACK)
                .add(COW_FESTIVAL, 18000L, GENERAL_BEDROOM)
                .add(SHEEP_FESTIVAL, 0L, GENERAL_BEDROOM)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_JENNI)
                .add(SHEEP_FESTIVAL, 18000L, GENERAL_BEDROOM)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT1)
                .add(STARRY_NIGHT, 7500L, GENERAL_BEDROOM)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT1)
                .add(PARK_STARRY_NIGHT_SEAT3, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_OAK)
                .add(NEW_YEARS_EVE, 6000L, GENERAL_BEDROOM)
                .add(NEW_YEARS_EVE, 13000L, GENERAL_GARDEN)
                .add(NEW_YEARS_EVE, 17000L, PARK_OAK)
                .build();

        ScheduleBuilder.create(MILKMAID, GENERAL_BED)
                .add(SPRING, SUNDAY, 0L, GENERAL_BED)
                .add(SPRING, SUNDAY, 6000L, GENERAL_CUSTOMER)
                .add(SPRING, SUNDAY, 6250L, GENERAL_STORE_FRONT)
                .add(SPRING, SUNDAY, 6500L, CHURCH_LEFT)
                .add(SPRING, SUNDAY, 16000L, PARK_CENTRE)
                .add(SPRING, SUNDAY, 20000L, FISHING_POND_BACK)
                .add(SPRING, SUNDAY, 23500L, GENERAL_STORE_FRONT)
                .add(SPRING, SUNDAY, 23750L, GENERAL_CUSTOMER)
                .add(SPRING, SUNDAY, 24000L, GENERAL_BED)
                .add(SPRING, MONDAY, 0L, GENERAL_BED)
                .add(SPRING, MONDAY, 8000L, BARN_LEFT_PEN)
                .add(SPRING, MONDAY, 10000L, BARN_RIGHT_PEN)
                .add(SPRING, MONDAY, 15000L, BARN_DOOR)
                .add(SPRING, MONDAY, 17000L, FISHER_LEFT)
                .add(SPRING, MONDAY, 20000L, FISHING_POND_BACK)
                .add(SPRING, MONDAY, 24000L, GENERAL_BED)
                .add(COOKING_CONTEST, 0L, GENERAL_BED)
                .add(COOKING_CONTEST, 6000L, PARK_TABLE)
                .add(COOKING_CONTEST, 16000L, PARK_CUSTOMER)
                .add(COOKING_CONTEST, 18000L, GENERAL_BED)
                .add(COOKING_CONTEST, 20000L, FISHING_POND_BACK)
                .add(COOKING_CONTEST, 24000L, GENERAL_BED)
                .add(NEW_YEARS, 0L, GENERAL_BED)
                .add(NEW_YEARS, 7000L, GENERAL_GARDEN)
                .add(NEW_YEARS, 12000L, PARK_OAK)
                .add(NEW_YEARS, 20000L, GENERAL_GARDEN)
                .add(NEW_YEARS, 22000L, GENERAL_BED)
                .add(COW_FESTIVAL, 0L, GENERAL_BED)
                .add(COW_FESTIVAL, 6000L, PARK_COW_JUDGE)
                .add(COW_FESTIVAL, 19000L, GENERAL_GARDEN)
                .add(COW_FESTIVAL, 22000L, GENERAL_BED)
                .add(SHEEP_FESTIVAL, 0L, GENERAL_BED)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_SHOP)
                .add(SHEEP_FESTIVAL, 18000L, GENERAL_BED)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT2)
                .add(STARRY_NIGHT, 8000L, GENERAL_BED)
                .add(STARRY_NIGHT, 10000L, GENERAL_STORE_FRONT)
                .add(STARRY_NIGHT, 15000L, GENERAL_GARDEN)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT2)
                .add(PARK_STARRY_NIGHT_SEAT4, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_OAK)
                .add(NEW_YEARS_EVE, 6000L, GENERAL_BED)
                .add(NEW_YEARS_EVE, 13000L, GENERAL_GARDEN)
                .add(NEW_YEARS_EVE, 17000L, PARK_OAK)
                .build();

        ScheduleBuilder.create(BARN_OWNER, BARN_INSIDE)
                .add(SPRING, SUNDAY, 0L, BARN_INSIDE)
                .add(SPRING, SUNDAY, 10000L, GENERAL_BEDROOM)
                .add(SPRING, SUNDAY, 13000L, CAFE_FRONT)
                .add(SPRING, SUNDAY, 16000L, PARK_CENTRE)
                .add(SPRING, SUNDAY, 19000L, GENERAL_BEDROOM)
                .add(SPRING, SUNDAY, 21000L, BARN_INSIDE)
                .add(SPRING, MONDAY, 0L, BARN_INSIDE)
                .add(SPRING, MONDAY, 10000L, BARN_WORK)
                .add(SPRING, MONDAY, 15000L, GENERAL_CUSTOMER)
                .add(SPRING, MONDAY, 17000L, PARK_CENTRE)
                .add(SPRING, MONDAY, 19000L, GENERAL_BEDROOM)
                .add(SPRING, MONDAY, 22000L, BARN_INSIDE)
                .add(COOKING_CONTEST, 0L, BARN_INSIDE)
                .add(COOKING_CONTEST, 10000L, BARN_INSIDE)
                .add(COOKING_CONTEST, 17000L, BARN_DOOR)
                .add(COOKING_CONTEST, 19000L, GENERAL_BEDROOM)
                .add(COOKING_CONTEST, 23500L, BARN_INSIDE)
                .add(COW_FESTIVAL, 0L, BARN_INSIDE)
                .add(COW_FESTIVAL, 6000L, PARK_COW_BARN)
                .add(COW_FESTIVAL, 19000L, BARN_DOOR)
                .add(COW_FESTIVAL, 22000L, BARN_INSIDE)
                .add(SHEEP_FESTIVAL, 0L, BARN_INSIDE)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_JUDGE)
                .add(SHEEP_FESTIVAL, 19000L, BARN_DOOR)
                .add(SHEEP_FESTIVAL, 22000L, BARN_INSIDE)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT1)
                .add(STARRY_NIGHT, 6000L, BARN_INSIDE)
                .add(STARRY_NIGHT, 15000L, GENERAL_BEDROOM)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT1)
                .add(PARK_STARRY_NIGHT_SEAT2, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_LEFT)
                .add(NEW_YEARS_EVE, 6000L, BARN_INSIDE)
                .add(NEW_YEARS_EVE, 13000L, BARN_DOOR)
                .add(NEW_YEARS_EVE, 17000L, PARK_LEFT)
                .build();

        ScheduleBuilder.create(POULTRY, POULTRY_CENTRE)
                .add(SPRING, SUNDAY, 0L, POULTRY_CENTRE)
                .add(SPRING, SUNDAY, 6000L, CARPENTER_FRONT)
                .add(SPRING, SUNDAY, 7500L, CHURCH_RIGHT)
                .add(SPRING, SUNDAY, 12000L, POULTRY_CENTRE)
                .add(SPRING, SUNDAY, 15000L, PARK_BENCH)
                .add(SPRING, SUNDAY, 18000L, POULTRY_CENTRE)
                .add(SPRING, MONDAY, 0L, POULTRY_CENTRE)
                .add(SPRING, MONDAY, 6000L, POULTRY_WORK)
                .add(SPRING, MONDAY, 13000L, GENERAL_STORE_FRONT)
                .add(SPRING, MONDAY, 15000L, PARK_BENCH)
                .add(SPRING, MONDAY, 18000L, POULTRY_CENTRE)
                .add(COOKING_CONTEST, 0L, POULTRY_CENTRE)
                .add(COOKING_CONTEST, 6000L, PARK_BENCH)
                .add(COOKING_CONTEST, 11000L, POULTRY_DOOR)
                .add(COOKING_CONTEST, 13000L, POULTRY_CENTRE)
                .add(COW_FESTIVAL, 0L, POULTRY_CENTRE)
                .add(COW_FESTIVAL, 6000L, PARK_CUSTOMER)
                .add(COW_FESTIVAL, 18000L, POULTRY_CENTRE)
                .add(SHEEP_FESTIVAL, 0L, POULTRY_CENTRE)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_ASHLEE)
                .add(SHEEP_FESTIVAL, 18000L, POULTRY_CENTRE)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT2)
                .add(STARRY_NIGHT, 6000L, POULTRY_CENTRE)
                .add(STARRY_NIGHT, 13000L, GENERAL_STORE_FRONT)
                .add(STARRY_NIGHT, 15000L, PARK_BENCH)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT2)
                .add(PARK_STARRY_NIGHT_SEAT4, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_LEFT)
                .add(NEW_YEARS_EVE, 6000L, POULTRY_CENTRE)
                .add(NEW_YEARS_EVE, 13000L, POULTRY_DOOR)
                .add(NEW_YEARS_EVE, 17000L, PARK_LEFT)
                .build();

        ScheduleBuilder.create(FISHERMAN, FISHING_HUT_UPSTAIRS)
                .add(SPRING, SUNDAY, 0L, FISHING_HUT_UPSTAIRS)
                .add(SPRING, SUNDAY, 6000L, FISHING_POND_PIER)
                .add(SPRING, SUNDAY, 9000L, GODDESS_POND_FRONT)
                .add(SPRING, SUNDAY, 12000L, FISHING_HUT_DOWNSTAIRS)
                .add(SPRING, SUNDAY, 15000L, FISHING_POND_PIER)
                .add(SPRING, SUNDAY, 18000L, FISHING_HUT_UPSTAIRS)
                .add(SPRING, TUESDAY, 0L, FISHING_HUT_UPSTAIRS)
                .add(SPRING, TUESDAY, 6000L, FISHING_POND_PIER)
                .add(SPRING, TUESDAY, 10000L, GODDESS_POND_FRONT)
                .add(SPRING, TUESDAY, 12000L, FISHING_HUT_DOWNSTAIRS)
                .add(SPRING, TUESDAY, 13000L, FISHING_HUT_WORK)
                .add(SPRING, TUESDAY, 19000L, FISHING_POND_PIER)
                .add(SPRING, TUESDAY, 22000L, FISHING_HUT_UPSTAIRS)
                .add(SPRING, SATURDAY, 0L, FISHING_HUT_UPSTAIRS)
                .add(SPRING, SATURDAY, 6000L, GODDESS_POND_FRONT)
                .add(SPRING, SATURDAY, 8000L, FISHING_POND_PIER)
                .add(SPRING, SATURDAY, 13000L, FISHING_HUT_DOWNSTAIRS)
                .add(SPRING, SATURDAY, 15000L, FISHING_POND_PIER)
                .add(SPRING, SATURDAY, 18000L, FISHING_HUT_DOWNSTAIRS)
                .add(SPRING, SATURDAY, 19500L, FISHING_POND_PIER)
                .add(SPRING, SATURDAY, 22000L, FISHING_HUT_UPSTAIRS)
                .add(COOKING_CONTEST, 0L, FISHING_HUT_UPSTAIRS)
                .add(COOKING_CONTEST, 6000L, GODDESS_POND_FRONT)
                .add(COOKING_CONTEST, 7000L, FISHING_POND_PIER)
                .add(COOKING_CONTEST, 13000L, PARK_LEFT)
                .add(COOKING_CONTEST, 16000L, PARK_CUSTOMER)
                .add(COOKING_CONTEST, 17500L, FISHING_POND_PIER)
                .add(COOKING_CONTEST, 20000L, FISHING_HUT_DOWNSTAIRS)
                .add(COOKING_CONTEST, 22000L, FISHING_HUT_UPSTAIRS)
                .add(COW_FESTIVAL, 0L, FISHING_HUT_DOWNSTAIRS)
                .add(COW_FESTIVAL, 6000L, PARK_BUSH)
                .add(COW_FESTIVAL, 18000L, FISHING_HUT_DOWNSTAIRS)
                .add(SHEEP_FESTIVAL, 0L, FISHING_HUT_DOWNSTAIRS)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_JAKOB)
                .add(SHEEP_FESTIVAL, 18000L, FISHING_HUT_DOWNSTAIRS)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT3)
                .add(STARRY_NIGHT, 6000L, FISHING_POND_PIER)
                .add(STARRY_NIGHT, 10000L, GODDESS_POND_FRONT)
                .add(STARRY_NIGHT, 12000L, FISHING_HUT_DOWNSTAIRS)
                .add(STARRY_NIGHT, 13000L, FISHING_HUT_WORK)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT3)
                .add(PARK_STARRY_NIGHT_SEAT3, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_BOTTOM)
                .add(NEW_YEARS_EVE, 6000L, FISHING_HUT_UPSTAIRS)
                .add(NEW_YEARS_EVE, 13000L, FISHING_HUT_DOWNSTAIRS)
                .add(NEW_YEARS_EVE, 17000L, PARK_BOTTOM)
                .build();

        ScheduleBuilder.create(CAFE_OWNER, CAFE_BALCONY)
                .add(SPRING, SUNDAY, 0L, CAFE_BALCONY)
                .add(SPRING, SUNDAY, 6000L, GODDESS_POND_FRONT_LEFT)
                .add(SPRING, SUNDAY, 7000L, CHURCH_INSIDE)
                .add(SPRING, SUNDAY, 8500L, CAFE_TILL)
                .add(SPRING, SUNDAY, 17000L, PARK_TABLE)
                .add(SPRING, SUNDAY, 20000L, CAFE_BALCONY)
                .add(SPRING, MONDAY, 0L, CAFE_BALCONY)
                .add(SPRING, MONDAY, 8000L, CAFE_TILL)
                .add(SPRING, MONDAY, 17000L, CAFE_CUSTOMER)
                .add(SPRING, MONDAY, 18000L, CAFE_FRONT)
                .add(SPRING, MONDAY, 19000L, PARK_TABLE)
                .add(SPRING, MONDAY, 22000L, CAFE_BALCONY)
                .add(SPRING, SATURDAY, 0L, CAFE_BALCONY)
                .add(SPRING, SATURDAY, 6000L, GODDESS_POND_FRONT_LEFT)
                .add(SPRING, SATURDAY, 8000L, CAFE_TILL)
                .add(SPRING, SATURDAY, 17000L, CAFE_CUSTOMER)
                .add(SPRING, SATURDAY, 18000L, CAFE_FRONT)
                .add(SPRING, SATURDAY, 19000L, PARK_TABLE)
                .add(SPRING, SATURDAY, 22000L, CAFE_BALCONY)
                .add(COOKING_CONTEST, 0L, CAFE_BALCONY)
                .add(COOKING_CONTEST, 6000L, PARK_STALL)
                .add(COOKING_CONTEST, 18000L, CAFE_BALCONY)
                .add(COW_FESTIVAL, 0L, CAFE_BALCONY)
                .add(COW_FESTIVAL, 6000L, PARK_CAFE)
                .add(COW_FESTIVAL, 18000L, CAFE_BALCONY)
                .add(SHEEP_FESTIVAL, 0L, CAFE_BALCONY)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_LIARA)
                .add(SHEEP_FESTIVAL, 18000L, CAFE_BALCONY)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT1)
                .add(STARRY_NIGHT, 8000L, CAFE_BALCONY)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT1)
                .add(PARK_STARRY_NIGHT_SEAT1, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_SPRUCE)
                .add(NEW_YEARS_EVE, 6000L, CAFE_BALCONY)
                .add(NEW_YEARS_EVE, 13000L, CAFE_FRONT)
                .add(NEW_YEARS_EVE, 17000L, PARK_SPRUCE)
                .build();

        ScheduleBuilder.create(CAFE_GRANNY, CAFE_KITCHEN)
                .add(SPRING, SUNDAY, 0L, CAFE_KITCHEN)
                .add(SPRING, SATURDAY, 6000L, CHURCH_PEW_CENTRE)
                .add(SPRING, SUNDAY, 17000L, FISHING_POND_RIGHT)
                .add(SPRING, SUNDAY, 20000L, CAFE_KITCHEN)
                .add(SPRING, MONDAY, 0L, CAFE_KITCHEN)
                .add(SPRING, MONDAY, 6000L, GODDESS_POND_FRONT_LEFT)
                .add(SPRING, MONDAY, 6500L, CAFE_FRONT)
                .add(SPRING, MONDAY, 17000L, FISHING_POND_RIGHT)
                .add(SPRING, MONDAY, 19000L, CAFE_KITCHEN)
                .add(SPRING, FRIDAY, 0L, CAFE_KITCHEN)
                .add(SPRING, FRIDAY, 9500L, GODDESS_POND_FRONT_LEFT)
                .add(SPRING, FRIDAY, 14000L, CAFE_FRONT)
                .add(SPRING, FRIDAY, 16000L, CAFE_KITCHEN)
                .add(SPRING, FRIDAY, 20000L, FISHING_POND_RIGHT)
                .add(SPRING, FRIDAY, 22000L, CAFE_KITCHEN)
                .add(SPRING, SATURDAY, 0L, CAFE_KITCHEN)
                .add(SPRING, SATURDAY, 6000L, GODDESS_POND_FRONT_LEFT)
                .add(SPRING, SATURDAY, 10000L, CAFE_FRONT)
                .add(SPRING, SATURDAY, 15000L, CAFE_KITCHEN)
                .add(SPRING, SATURDAY, 17000L, FISHING_POND_RIGHT)
                .add(SPRING, SATURDAY, 19000L, CAFE_KITCHEN)
                .add(COOKING_CONTEST, 0L, CAFE_KITCHEN)
                .add(COOKING_CONTEST, 6000L, PARK_CAFE)
                .add(COOKING_CONTEST, 18000L, CAFE_KITCHEN)
                .add(COW_FESTIVAL, 0L, CAFE_KITCHEN)
                .add(COW_FESTIVAL, 6000L, PARK_COW_SEATS)
                .add(COW_FESTIVAL, 18000L, CAFE_KITCHEN)
                .add(SHEEP_FESTIVAL, 0L, CAFE_KITCHEN)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_GRANNY)
                .add(SHEEP_FESTIVAL, 18000L, CAFE_KITCHEN)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT2)
                .add(STARRY_NIGHT, 6000L, GODDESS_POND_FRONT_LEFT)
                .add(STARRY_NIGHT, 8500L, CAFE_FRONT)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT2)
                .add(PARK_STARRY_NIGHT_SEAT2, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_SPRUCE)
                .add(NEW_YEARS_EVE, 6000L, CAFE_KITCHEN)
                .add(NEW_YEARS_EVE, 13000L, GODDESS_POND_FRONT_RIGHT)
                .add(NEW_YEARS_EVE, 17000L, PARK_SPRUCE)
                .build();

        ScheduleBuilder.create(BLACKSMITH, BLACKSMITH_FURNACE)
                .add(SPRING, SUNDAY, 0L, BLACKSMITH_FURNACE)
                .add(SPRING, SUNDAY, 6000L, CAFE_DOOR)
                .add(SPRING, SUNDAY, 8000L, BLACKSMITH_FRONT)
                .add(SPRING, SUNDAY, 9500L, BLACKSMITH_FURNACE)
                .add(SPRING, SUNDAY, 10000L, BLACKSMITH_WORK)
                .add(SPRING, SUNDAY, 17000L, TOWNHALL_ENTRANCE)
                .add(SPRING, SUNDAY, 20000L, PARK_OAK)
                .add(SPRING, SUNDAY, 23000L, BLACKSMITH_FURNACE)
                .add(SPRING, THURSDAY, 0L, BLACKSMITH_FURNACE)
                .add(SPRING, THURSDAY, 6000L, CAFE_DOOR)
                .add(SPRING, THURSDAY, 10000L, CAFE_STAIRS)
                .add(SPRING, THURSDAY, 13000L, MINE_RIGHT)
                .add(SPRING, THURSDAY, 16000L, CAFE_DOOR)
                .add(SPRING, THURSDAY, 18000L, BLACKMSITH_DOOR)
                .add(SPRING, THURSDAY, 20000L, PARK_OAK)
                .add(SPRING, THURSDAY, 23000L, BLACKSMITH_FURNACE)
                .add(SPRING, FRIDAY, 0L, BLACKSMITH_FURNACE)
                .add(SPRING, FRIDAY, 6000L, CAFE_DOOR)
                .add(SPRING, FRIDAY, 8000L, BLACKSMITH_FRONT)
                .add(SPRING, FRIDAY, 9500L, BLACKSMITH_FURNACE)
                .add(SPRING, FRIDAY, 10000L, BLACKSMITH_WORK)
                .add(SPRING, FRIDAY, 17000L, TOWNHALL_ENTRANCE)
                .add(SPRING, FRIDAY, 20000L, PARK_OAK)
                .add(SPRING, FRIDAY, 23000L, BLACKSMITH_FURNACE)
                .add(COW_FESTIVAL, 0L, BLACKSMITH_FURNACE)
                .add(COW_FESTIVAL, 6000L, PARK_COW_BACK_LEFT)
                .add(COW_FESTIVAL, 18000L, BLACKSMITH_FURNACE)
                .add(SHEEP_FESTIVAL, 0L, BLACKSMITH_FURNACE)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_DANIERU)
                .add(SHEEP_FESTIVAL, 18000L, BLACKSMITH_FURNACE)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT1)
                .add(STARRY_NIGHT, 6000L, CAFE_DOOR)
                .add(STARRY_NIGHT, 8000L, BLACKSMITH_FRONT)
                .add(STARRY_NIGHT, 9500L, BLACKSMITH_FURNACE)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT1)
                .add(PARK_STARRY_NIGHT_SEAT3, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_BUSH)
                .add(NEW_YEARS_EVE, 6000L, BLACKSMITH_FURNACE)
                .add(NEW_YEARS_EVE, 13000L, BLACKSMITH_FRONT)
                .add(NEW_YEARS_EVE, 17000L, PARK_BUSH)
                .build();

        ScheduleBuilder.create(CLOCKMAKER, CLOCKMAKER_DOWNSTAIRS)
                .add(SPRING, SUNDAY, 0L, CLOCKMAKER_DOWNSTAIRS)
                .add(SPRING, SUNDAY, 8000L, CHURCH_PEW_BACK_RIGHT)
                .add(SPRING, SUNDAY, 11000L, TOWNHALL_RIGHT)
                .add(SPRING, SUNDAY, 14000L, GODDESS_POND_BACK)
                .add(SPRING, SUNDAY, 16000L, PARK_LEFT)
                .add(SPRING, SUNDAY, 18000L, CLOCKMAKER_DOWNSTAIRS)
                .add(SPRING, MONDAY, 0L, CLOCKMAKER_DOWNSTAIRS)
                .add(SPRING, MONDAY, 8000L, CLOCKMAKER_WORK)
                .add(SPRING, MONDAY, 15500L, FISHING_POND_LEFT)
                .add(SPRING, MONDAY, 16000L, PARK_LEFT)
                .add(SPRING, MONDAY, 18000L, CLOCKMAKER_DOWNSTAIRS)
                .add(SPRING, SATURDAY, 0L, CLOCKMAKER_DOWNSTAIRS)
                .add(SPRING, SATURDAY, 8000L, CAFE_CUSTOMER)
                .add(SPRING, SATURDAY, 11000L, TOWNHALL_RIGHT_OF_STAGE)
                .add(SPRING, SATURDAY, 14000L, FISHING_POND_LEFT)
                .add(SPRING, SATURDAY, 16000L, PARK_LEFT)
                .add(SPRING, SATURDAY, 18000L, CLOCKMAKER_DOWNSTAIRS)
                .add(NEW_YEARS, 0L, CLOCKMAKER_DOWNSTAIRS)
                .add(NEW_YEARS, 7000L, CLOCKMAKER_DOOR)
                .add(NEW_YEARS, 12000L, PARK_SPRUCE)
                .add(NEW_YEARS, 20000L, CLOCKMAKER_DOOR)
                .add(NEW_YEARS, 22000L, CLOCKMAKER_DOWNSTAIRS)
                .add(COW_FESTIVAL, 0L, CLOCKMAKER_DOWNSTAIRS)
                .add(COW_FESTIVAL, 6000L, PARK_TABLE)
                .add(COW_FESTIVAL, 18000L, CLOCKMAKER_DOWNSTAIRS)
                .add(SHEEP_FESTIVAL, 0L, CLOCKMAKER_DOWNSTAIRS)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_TIBERIUS)
                .add(SHEEP_FESTIVAL, 18000L, CLOCKMAKER_DOWNSTAIRS)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT1)
                .add(STARRY_NIGHT, 8000L, CHURCH_PEW_BACK_RIGHT)
                .add(STARRY_NIGHT, 11000L, TOWNHALL_RIGHT)
                .add(STARRY_NIGHT, 14000L, GODDESS_POND_BACK)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT1)
                .add(PARK_STARRY_NIGHT_SEAT1, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_BACK_LEFT)
                .add(NEW_YEARS_EVE, 6000L, CLOCKMAKER_DOWNSTAIRS)
                .add(NEW_YEARS_EVE, 13000L, CLOCKMAKER_DOOR)
                .add(NEW_YEARS_EVE, 17000L, PARK_BACK_LEFT)
                .build();

        ScheduleBuilder.create(CLOCKMAKER_CHILD, CLOCKMAKER_UPSTAIRS)
                .add(SPRING, SUNDAY, 0L, CLOCKMAKER_UPSTAIRS)
                .add(SPRING, SUNDAY, 8000L, CHURCH_PEW_BACK_RIGHT)
                .add(SPRING, SUNDAY, 10000L, POULTRY_DOOR)
                .add(SPRING, SUNDAY, 12000L, BARN_DOOR)
                .add(SPRING, SUNDAY, 16000L, TOWNHALL_LEFT)
                .add(SPRING, SUNDAY, 18000L, CLOCKMAKER_UPSTAIRS)
                .add(SPRING, MONDAY, 0L, CLOCKMAKER_UPSTAIRS)
                .add(SPRING, MONDAY, 8000L, BARN_DOOR)
                .add(SPRING, MONDAY, 10000L, POULTRY_DOOR)
                .add(SPRING, MONDAY, 14000L, FISHING_POND_LEFT)
                .add(SPRING, MONDAY, 16000L, PARK_SPRUCE)
                .add(SPRING, MONDAY, 18000L, CLOCKMAKER_UPSTAIRS)
                .add(NEW_YEARS, 0L, CLOCKMAKER_UPSTAIRS)
                .add(NEW_YEARS, 7000L, CLOCKMAKER_DOWNSTAIRS)
                .add(NEW_YEARS, 12000L, PARK_SPRUCE)
                .add(NEW_YEARS, 19000L, CLOCKMAKER_DOWNSTAIRS)
                .add(NEW_YEARS, 20000L, CLOCKMAKER_UPSTAIRS)
                .add(COW_FESTIVAL, 0L, CLOCKMAKER_UPSTAIRS)
                .add(COW_FESTIVAL, 6000L, PARK_TABLE)
                .add(COW_FESTIVAL, 18000L, CLOCKMAKER_UPSTAIRS)
                .add(SHEEP_FESTIVAL, 0L, CLOCKMAKER_UPSTAIRS)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_TIBERIUS)
                .add(SHEEP_FESTIVAL, 18000L, CLOCKMAKER_UPSTAIRS)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT2)
                .add(STARRY_NIGHT, 8000L, BARN_DOOR)
                .add(STARRY_NIGHT, 10000L, POULTRY_DOOR)
                .add(STARRY_NIGHT, 14000L, FISHING_POND_LEFT)
                .add(STARRY_NIGHT, 16000L, PARK_SPRUCE)
                .add(STARRY_NIGHT, 18000L, PARK_STARRY_NIGHT_SEAT2)
                .add(PARK_STARRY_NIGHT_SEAT2, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_BACK_LEFT)
                .add(NEW_YEARS_EVE, 6000L, CLOCKMAKER_UPSTAIRS)
                .add(NEW_YEARS_EVE, 13000L, CLOCKMAKER_DOWNSTAIRS)
                .add(NEW_YEARS_EVE, 17000L, PARK_BACK_LEFT)
                .build();

        ScheduleBuilder.create(PRIEST, TOWNHALL_ADULT_BED)
                .add(SPRING, SUNDAY, 0L, TOWNHALL_ADULT_BED)
                .add(SPRING, SUNDAY, 6000L, CHURCH_FRONT)
                .add(SPRING, SUNDAY, 7000L, CHURCH_WORK)
                .add(SPRING, SUNDAY, 17000L, GODDESS_POND_FRONT_RIGHT)
                .add(SPRING, SUNDAY, 19000L, GODDESS_POND_FRONT)
                .add(SPRING, SUNDAY, 22000L, TOWNHALL_ADULT_BED)
                .add(SPRING, MONDAY, 0L, TOWNHALL_ADULT_BED)
                .add(SPRING, MONDAY, 6000L, MINE_BACK)
                .add(SPRING, MONDAY, 9000L, CHURCH_INSIDE)
                .add(SPRING, MONDAY, 17500L, FISHING_HUT_RIGHT)
                .add(SPRING, MONDAY, 19000L, TOWNHALL_LEFT_OF_STAGE)
                .add(SPRING, MONDAY, 22000L, TOWNHALL_ADULT_BED)
                .add(NEW_YEARS, 0L, TOWNHALL_ADULT_BED)
                .add(NEW_YEARS, 7000L, TOWNHALL_ENTRANCE)
                .add(NEW_YEARS, 12000L, PARK_BENCH)
                .add(NEW_YEARS, 20000L, TOWNHALL_ENTRANCE)
                .add(NEW_YEARS, 22000L, TOWNHALL_ADULT_BED)
                .add(COW_FESTIVAL, 0L, TOWNHALL_ADULT_BED)
                .add(COW_FESTIVAL, 6000L, PARK_COW_EDGE)
                .add(COW_FESTIVAL, 18000L, TOWNHALL_ADULT_BED)
                .add(SHEEP_FESTIVAL, 0L, TOWNHALL_ADULT_BED)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_MAYOR)
                .add(SHEEP_FESTIVAL, 18000L, TOWNHALL_ADULT_BED)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT3)
                .add(STARRY_NIGHT, 6000L, MINE_BACK)
                .add(STARRY_NIGHT, 9000L, CHURCH_INSIDE)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT3)
                .add(PARK_STARRY_NIGHT_SEAT3, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_CUSTOMER)
                .add(NEW_YEARS_EVE, 6000L, TOWNHALL_ADULT_BED)
                .add(NEW_YEARS_EVE, 13000L, CHURCH_INSIDE)
                .add(NEW_YEARS_EVE, 17000L, PARK_CUSTOMER)
                .build();

        ScheduleBuilder.create(MAYOR, TOWNHALL_STAGE)
                .add(SPRING, SUNDAY, 0L, TOWNHALL_ADULT_BED)
                .add(SPRING, SUNDAY, 6000L, TOWNHALL_FRONT_OF_STAGE)
                .add(SPRING, SUNDAY, 9000L, TOWNHALL_STAGE)
                .add(SPRING, SUNDAY, 15000L, CAFE_BALCONY)
                .add(SPRING, SUNDAY, 19000L, TOWNHALL_LEFT)
                .add(SPRING, SUNDAY, 22000L, TOWNHALL_ADULT_BED)
                .add(COOKING_CONTEST, 0L, TOWNHALL_ADULT_BED)
                .add(COOKING_CONTEST, 6000L, PARK_BUSH)
                .add(COOKING_CONTEST, 19000L, TOWNHALL_FRONT_OF_STAGE)
                .add(COOKING_CONTEST, 22000L, TOWNHALL_ADULT_BED)
                .add(NEW_YEARS, 0L, TOWNHALL_ADULT_BED)
                .add(NEW_YEARS, 7000L, TOWNHALL_STAGE)
                .add(NEW_YEARS, 12000L, PARK_PODIUM)
                .add(NEW_YEARS, 20000L, TOWNHALL_STAGE)
                .add(NEW_YEARS, 22000L, TOWNHALL_ADULT_BED)
                .add(COW_FESTIVAL, 0L, TOWNHALL_STAGE)
                .add(COW_FESTIVAL, 6000L, PARK_COW_EDGE)
                .add(COW_FESTIVAL, 18000L, TOWNHALL_STAGE)
                .add(SHEEP_FESTIVAL, 0L, TOWNHALL_STAGE)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_MAYOR)
                .add(SHEEP_FESTIVAL, 18000L, TOWNHALL_STAGE)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT4)
                .add(STARRY_NIGHT, 6000L, TOWNHALL_FRONT_OF_STAGE)
                .add(STARRY_NIGHT, 9000L, TOWNHALL_STAGE)
                .add(STARRY_NIGHT, 15000L, CAFE_BALCONY)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT4)
                .add(PARK_STARRY_NIGHT_SEAT4, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_CUSTOMER)
                .add(NEW_YEARS_EVE, 6000L, TOWNHALL_ADULT_BED)
                .add(NEW_YEARS_EVE, 13000L, TOWNHALL_STAGE)
                .add(NEW_YEARS_EVE, 17000L, PARK_CUSTOMER)
                .build();

        ScheduleBuilder.create(DAUGHTER_ADULT, TOWNHALL_TEEN_BED)
                .add(SPRING, SUNDAY, 0L, TOWNHALL_TEEN_BED)
                .add(SPRING, SUNDAY, 7000L, CHURCH_PEW_FRONT_RIGHT)
                .add(SPRING, SUNDAY, 10000L, CAFE_KITCHEN)
                .add(SPRING, SUNDAY, 13000L, POULTRY_FRONT)
                .add(SPRING, SUNDAY, 15000L, TOWNHALL_RIGHT)
                .add(SPRING, SUNDAY, 19000L, TOWNHALL_TEEN_BED)
                .add(SPRING, MONDAY, 0L, TOWNHALL_TEEN_BED)
                .add(SPRING, MONDAY, 7000L, CAFE_KITCHEN)
                .add(SPRING, MONDAY, 10000L, FISHING_HUT_DOOR)
                .add(SPRING, MONDAY, 15000L, TOWNHALL_RIGHT)
                .add(SPRING, MONDAY, 19000L, TOWNHALL_TEEN_BED)
                .add(NEW_YEARS, 0L, TOWNHALL_TEEN_BED)
                .add(NEW_YEARS, 7000L, TOWNHALL_RIGHT)
                .add(NEW_YEARS, 12000L, PARK_BENCH)
                .add(NEW_YEARS, 20000L, TOWNHALL_RIGHT)
                .add(NEW_YEARS, 22000L, TOWNHALL_TEEN_BED)
                .add(COW_FESTIVAL, 0L, TOWNHALL_TEEN_BED)
                .add(COW_FESTIVAL, 6000L, PARK_COW_EDGE)
                .add(COW_FESTIVAL, 18000L, TOWNHALL_TEEN_BED)
                .add(SHEEP_FESTIVAL, 0L, TOWNHALL_TEEN_BED)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_MAYOR)
                .add(SHEEP_FESTIVAL, 18000L, TOWNHALL_TEEN_BED)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT1)
                .add(STARRY_NIGHT, 6000L, CAFE_KITCHEN)
                .add(STARRY_NIGHT, 10000L, FISHING_HUT_DOOR)
                .add(STARRY_NIGHT, 15000L, TOWNHALL_RIGHT)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT1)
                .add(PARK_STARRY_NIGHT_SEAT1, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_CUSTOMER)
                .add(NEW_YEARS_EVE, 6000L, TOWNHALL_TEEN_BED)
                .add(NEW_YEARS_EVE, 13000L, TOWNHALL_RIGHT)
                .add(NEW_YEARS_EVE, 17000L, PARK_CUSTOMER)
                .build();

        ScheduleBuilder.create(DAUGHTER_CHILD, TOWNHALL_CHILD_BED)
                .add(SPRING, SUNDAY, 0L, TOWNHALL_CHILD_BED)
                .add(SPRING, SUNDAY, 8000L, CHURCH_PEW_FRONT_LEFT)
                .add(SPRING, SUNDAY, 10000L, POULTRY_DOOR)
                .add(SPRING, SUNDAY, 12000L, BARN_DOOR)
                .add(SPRING, SUNDAY, 14000L, TOWNHALL_LEFT)
                .add(SPRING, SUNDAY, 15000L, TOWNHALL_CHILD_BED)
                .add(SPRING, MONDAY, 0L, TOWNHALL_CHILD_BED)
                .add(SPRING, MONDAY, 8000L, BARN_DOOR)
                .add(SPRING, MONDAY, 10000L, POULTRY_DOOR)
                .add(SPRING, MONDAY, 12000L, TOWNHALL_LEFT)
                .add(SPRING, MONDAY, 15000L, TOWNHALL_CHILD_BED)
                .add(NEW_YEARS, 0L, TOWNHALL_CHILD_BED)
                .add(NEW_YEARS, 7000L, TOWNHALL_LEFT)
                .add(NEW_YEARS, 12000L, PARK_BENCH)
                .add(NEW_YEARS, 19000L, TOWNHALL_LEFT)
                .add(NEW_YEARS, 20000L, TOWNHALL_CHILD_BED)
                .add(COW_FESTIVAL, 0L, TOWNHALL_CHILD_BED)
                .add(COW_FESTIVAL, 6000L, PARK_COW_EDGE)
                .add(COW_FESTIVAL, 18000L, TOWNHALL_CHILD_BED)
                .add(SHEEP_FESTIVAL, 0L, TOWNHALL_CHILD_BED)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_MAYOR)
                .add(SHEEP_FESTIVAL, 18000L, TOWNHALL_CHILD_BED)
                .add(STARRY_NIGHT, 0L, PARK_STARRY_NIGHT_SEAT2)
                .add(STARRY_NIGHT, 8000L, BARN_DOOR)
                .add(STARRY_NIGHT, 10000L, POULTRY_DOOR)
                .add(STARRY_NIGHT, 13000L, TOWNHALL_LEFT)
                .add(STARRY_NIGHT, 17000L, PARK_STARRY_NIGHT_SEAT2)
                .add(PARK_STARRY_NIGHT_SEAT2, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_CUSTOMER)
                .add(NEW_YEARS_EVE, 6000L, TOWNHALL_CHILD_BED)
                .add(NEW_YEARS_EVE, 13000L, TOWNHALL_LEFT)
                .add(NEW_YEARS_EVE, 17000L, PARK_CUSTOMER)
                .build();

        ScheduleBuilder.create(TRADER, PARK_TRADER)
                .add(SPRING, SUNDAY, 0L, TOWNHALL_RIGHT)
                .add(SPRING, SUNDAY, 6000L, PARK_TRADER)
                .add(SPRING, SUNDAY, 11000L, GENERAL_CUSTOMER)
                .add(SPRING, SUNDAY, 13000L, GENERAL_GARDEN)
                .add(SPRING, SUNDAY, 16000L, GODDESS_POND_BACK_RIGHT)
                .add(COOKING_CONTEST, 0L, TOWNHALL_RIGHT)
                .add(COOKING_CONTEST, 6000L, PARK_TRADER)
                .add(COOKING_CONTEST, 19000L, GENERAL_GARDEN)
                .add(COOKING_CONTEST, 22000L, TOWNHALL_RIGHT)
                .add(NEW_YEARS, 0L, TOWNHALL_RIGHT)
                .add(NEW_YEARS, 10000L, TOWNHALL_ENTRANCE)
                .add(NEW_YEARS, 11500L, PARK_TRADER_RIGHT)
                .add(NEW_YEARS, 22500L, TOWNHALL_ENTRANCE)
                .add(NEW_YEARS, 23500L, TOWNHALL_RIGHT)
                .add(COW_FESTIVAL, 0L, TOWNHALL_RIGHT)
                .add(COW_FESTIVAL, 6000L, PARK_COW_BENCH)
                .add(COW_FESTIVAL, 18000L, TOWNHALL_RIGHT)
                .add(SHEEP_FESTIVAL, 0L, TOWNHALL_RIGHT)
                .add(SHEEP_FESTIVAL, 6000L, PARK_SHEEP_JENNI)
                .add(SHEEP_FESTIVAL, 18000L, TOWNHALL_RIGHT)
                .add(PARK_STARRY_NIGHT_SEAT2, isInvited)
                .add(NEW_YEARS_EVE, 0L, PARK_TABLE)
                .add(NEW_YEARS_EVE, 6000L, TOWNHALL_RIGHT)
                .add(NEW_YEARS_EVE, 13000L, TOWNHALL_ENTRANCE)
                .add(NEW_YEARS_EVE, 17000L, PARK_TABLE)
                .build();
    }
}
