package joshie.harvest.npc.gift.init;

import static joshie.harvest.npc.gift.Gifts.Category.*;
import static joshie.harvest.npc.gift.Gifts.assign;
import static net.minecraft.init.Items.*;

public class HFGiftVanillaItems {
    public static void init() {
        assign(IRON_SHOVEL, TOOLS);
        assign(IRON_PICKAXE, MINING, TOOLS);
        assign(IRON_AXE, TOOLS);
        assign(FLINT_AND_STEEL, TOOLS, DANGER);
        assign(APPLE, NATURE, COOKING, FARMING);
        assign(BOW, TOOLS, BATTLE);
        assign(ARROW, TOOLS, BATTLE);
        assign(COAL, MINING, CHEAP);
        assign(DIAMOND, MINING, PRETTY, RARE);
        assign(IRON_INGOT, MINING);
        assign(GOLD_INGOT, MINING);
        assign(IRON_SWORD, BATTLE);
        assign(WOODEN_SWORD, CHEAP, BATTLE);
        assign(WOODEN_SHOVEL, MINING, TOOLS, CHEAP);
        assign(WOODEN_PICKAXE, TOOLS, CHEAP);
        assign(WOODEN_AXE, TOOLS, CHEAP);
        assign(STONE_SWORD, CHEAP, BATTLE);
        assign(STONE_SHOVEL, TOOLS, CHEAP);
        assign(STONE_PICKAXE, MINING, TOOLS, CHEAP);
        assign(STONE_AXE, TOOLS, CHEAP);
        assign(DIAMOND_SWORD, RARE, BATTLE);
        assign(DIAMOND_SHOVEL, TOOLS, RARE);
        assign(DIAMOND_PICKAXE, MINING, TOOLS, RARE);
        assign(DIAMOND_AXE, TOOLS, RARE);
        assign(STICK, TOOLS, CHEAP);
        assign(BOWL, CHEAP);
        assign(MUSHROOM_STEW, NATURE, COOKING);
        assign(GOLDEN_SWORD, BATTLE);
        assign(GOLDEN_SHOVEL, TOOLS);
        assign(GOLDEN_PICKAXE, MINING, TOOLS);
        assign(GOLDEN_AXE, TOOLS);
        assign(STRING, NATURE, CHEAP, KNITTING);
        assign(FEATHER, CUTE, NATURE, ANIMALS, PRETTY, FARMING, GIRLY);
        assign(GUNPOWDER, CHEAP, DANGER);
        assign(WOODEN_HOE, TOOLS, CHEAP, FARMING);
        assign(STONE_HOE, TOOLS, FARMING);
        assign(IRON_HOE, TOOLS, FARMING);
        assign(DIAMOND_HOE, TOOLS, FARMING);
        assign(GOLDEN_HOE, TOOLS, FARMING);
        assign(WHEAT_SEEDS, NATURE, CHEAP, FARMING);
        assign(WHEAT, NATURE, COOKING, FARMING);
        assign(BREAD, COOKING);
        assign(LEATHER_HELMET, BATTLE);
        assign(LEATHER_CHESTPLATE, BATTLE);
        assign(LEATHER_LEGGINGS, BATTLE);
        assign(LEATHER_BOOTS, BATTLE);
        assign(CHAINMAIL_HELMET, BATTLE);
        assign(CHAINMAIL_CHESTPLATE, BATTLE);
        assign(CHAINMAIL_LEGGINGS, BATTLE);
        assign(CHAINMAIL_BOOTS, BATTLE);
        assign(IRON_HELMET, BATTLE);
        assign(IRON_CHESTPLATE, BATTLE);
        assign(IRON_LEGGINGS, BATTLE);
        assign(IRON_BOOTS, BATTLE);
        assign(DIAMOND_HELMET, PRETTY, RARE, BATTLE);
        assign(DIAMOND_CHESTPLATE, PRETTY, RARE, BATTLE);
        assign(DIAMOND_LEGGINGS, PRETTY, RARE, BATTLE);
        assign(DIAMOND_BOOTS, PRETTY, RARE, BATTLE);
        assign(GOLDEN_HELMET, BATTLE);
        assign(GOLDEN_CHESTPLATE, BATTLE);
        assign(GOLDEN_LEGGINGS, BATTLE);
        assign(GOLDEN_BOOTS, BATTLE);
        assign(FLINT, MINING, TOOLS, CHEAP);
        assign(PORKCHOP, NATURE, COOKING, FARMING);
        assign(COOKED_PORKCHOP, COOKING);
        assign(PAINTING, PRETTY);
        assign(GOLDEN_APPLE, RARE);
        assign(SIGN, CHEAP, CONSTRUCTION);
        assign(OAK_DOOR, CONSTRUCTION);
        assign(SPRUCE_DOOR, CONSTRUCTION);
        assign(BIRCH_DOOR, CONSTRUCTION);
        assign(JUNGLE_DOOR, CONSTRUCTION);
        assign(ACACIA_DOOR, CONSTRUCTION);
        assign(DARK_OAK_DOOR, CONSTRUCTION);
        assign(BUCKET, TOOLS);
        assign(WATER_BUCKET, WATERY);
        assign(LAVA_BUCKET, SCARY, DANGER);
        assign(MINECART, MINING);
        assign(SADDLE, CUTE, ANIMALS);
        assign(IRON_DOOR, CONSTRUCTION);
        assign(REDSTONE, MINING);
        assign(SNOWBALL, CUTE);
        assign(BOAT, WATERY);
        assign(LEATHER, FARMING);
        assign(MILK_BUCKET, ANIMALS, COOKING, FARMING);
        assign(BRICK, CONSTRUCTION);
        assign(CLAY_BALL, WATERY, CONSTRUCTION);
        assign(REEDS, NATURE, FARMING);
        assign(PAPER, CONSTRUCTION);
        assign(BOOK, CHEAP);
        assign(SLIME_BALL, SCARY, ANIMALS);
        assign(CHEST_MINECART, TECHNOLOGY);
        assign(FURNACE_MINECART, TECHNOLOGY);
        assign(EGG, NATURE, ANIMALS, COOKING);
        assign(COMPASS, TOOLS, TECHNOLOGY);
        assign(FISHING_ROD, ANIMALS, WATERY);
        assign(CLOCK, TOOLS, TECHNOLOGY);
        assign(GLOWSTONE_DUST, PRETTY, GIRLY);
        assign(FISH, NATURE, COOKING, WATERY);
        assign(COOKED_FISH, COOKING, WATERY);
        assign(DYE); //TODO: ASSIGN THE VARIATIONS
        assign(BONE, SCARY, DANGER);
        assign(SUGAR, CUTE, COOKING, GIRLY);
        assign(CAKE, CUTE, COOKING, GIRLY);
        assign(BED, CONSTRUCTION);
        assign(REPEATER, TECHNOLOGY);
        assign(COOKIE, CUTE, COOKING);
        assign(FILLED_MAP, TOOLS);
        assign(SHEARS, TOOLS);
        assign(MELON, NATURE, COOKING, FARMING);
        assign(PUMPKIN_SEEDS, NATURE, FARMING);
        assign(MELON_SEEDS, NATURE, FARMING);
        assign(BEEF, NATURE, COOKING, FARMING);
        assign(COOKED_BEEF, COOKING);
        assign(CHICKEN, NATURE, COOKING, FARMING);
        assign(COOKED_CHICKEN, COOKING);
        assign(ROTTEN_FLESH, SCARY, DANGER);
        assign(ENDER_PEARL, RARE, DANGER);
        assign(BLAZE_ROD, DANGER);
        assign(GHAST_TEAR, SCARY, RARE, DANGER);
        assign(GOLD_NUGGET, MINING, DANGER);
        assign(NETHER_WART, DANGER);
        assign(POTIONITEM, WATERY, DANGER);
        assign(GLASS_BOTTLE, COOKING, TOOLS);
        assign(SPIDER_EYE, SCARY, DANGER);
        assign(FERMENTED_SPIDER_EYE, SCARY, DANGER);
        assign(BLAZE_POWDER, DANGER);
        assign(MAGMA_CREAM, SCARY, DANGER);
        assign(BREWING_STAND, TECHNOLOGY);
        assign(CAULDRON, COOKING, CONSTRUCTION);
        assign(ENDER_EYE, SCARY, RARE, DANGER);
        assign(SPECKLED_MELON, PRETTY, DANGER);
        assign(SPAWN_EGG, DANGER);
        assign(EXPERIENCE_BOTTLE, PRETTY, RARE);
        assign(FIRE_CHARGE, SCARY, DANGER);
        assign(WRITABLE_BOOK, GIRLY);
        assign(WRITTEN_BOOK, GIRLY);
        assign(EMERALD, PRETTY, RARE);
        assign(ITEM_FRAME, PRETTY);
        assign(FLOWER_POT, CUTE, PRETTY);
        assign(CARROT, NATURE, COOKING, FARMING);
        assign(POTATO, NATURE, COOKING, FARMING);
        assign(BAKED_POTATO, COOKING);
        assign(POISONOUS_POTATO, SCARY, DANGER);
        assign(MAP, TOOLS);
        assign(GOLDEN_CARROT, PRETTY);
        assign(SKULL, SCARY, RARE);
        assign(CARROT_ON_A_STICK, ANIMALS);
        assign(NETHER_STAR, PRETTY);
        assign(PUMPKIN_PIE, COOKING);
        assign(FIREWORKS, PRETTY, GIRLY);
        assign(FIREWORK_CHARGE, DANGER);
        assign(ENCHANTED_BOOK, RARE);
        assign(COMPARATOR, TECHNOLOGY);
        assign(NETHERBRICK, CONSTRUCTION);
        assign(QUARTZ, MINING);
        assign(TNT_MINECART, SCARY, DANGER);
        assign(HOPPER_MINECART, TECHNOLOGY);
        assign(IRON_HORSE_ARMOR, ANIMALS, GIRLY);
        assign(GOLDEN_HORSE_ARMOR, ANIMALS, PRETTY, GIRLY);
        assign(DIAMOND_HORSE_ARMOR, ANIMALS, PRETTY, RARE, GIRLY);
        assign(LEAD, ANIMALS, FARMING);
        assign(NAME_TAG, ANIMALS);
        assign(COMMAND_BLOCK_MINECART, TECHNOLOGY);
        assign(RECORD_13, RARE);
        assign(RECORD_CAT, RARE);
        assign(RECORD_BLOCKS, RARE);
        assign(RECORD_CHIRP, RARE);
        assign(RECORD_FAR, RARE);
        assign(RECORD_MALL, RARE);
        assign(RECORD_MELLOHI, RARE);
        assign(RECORD_STAL, RARE);
        assign(RECORD_STRAD, RARE);
        assign(RECORD_WARD, RARE);
        assign(RECORD_11, RARE);
        assign(RECORD_WAIT, RARE);
        assign(PRISMARINE_SHARD, PRETTY, WATERY);
        assign(PRISMARINE_CRYSTALS, PRETTY, RARE, WATERY);
        assign(BANNER, BATTLE, KNITTING);
        assign(END_CRYSTAL, RARE, SCARY);
        assign(ELYTRA, RARE, TECHNOLOGY);
        assign(CHORUS_FRUIT, NATURE, SCARY, FARMING);
        assign(CHORUS_FRUIT_POPPED, NATURE, SCARY, FARMING);
        assign(BEETROOT_SEEDS, NATURE, CHEAP, FARMING);
        assign(BEETROOT, NATURE, COOKING, FARMING);
        assign(BEETROOT_SOUP, NATURE, COOKING);
    }
}