package joshie.harvest.npc.gift.init;

import joshie.harvest.npc.gift.GiftRegistry;

import static joshie.harvest.api.npc.gift.GiftCategory.*;
import static net.minecraft.init.Items.*;

public class HFGiftVanillaItems {
    public static void init() {
        GiftRegistry.INSTANCE.assign(IRON_SHOVEL, TOOLS);
        GiftRegistry.INSTANCE.assign(IRON_PICKAXE, MINING, TOOLS);
        GiftRegistry.INSTANCE.assign(IRON_AXE, TOOLS);
        GiftRegistry.INSTANCE.assign(FLINT_AND_STEEL, TOOLS, DANGER);
        GiftRegistry.INSTANCE.assign(APPLE, NATURE, COOKING, FARMING);
        GiftRegistry.INSTANCE.assign(BOW, TOOLS, BATTLE);
        GiftRegistry.INSTANCE.assign(ARROW, TOOLS, BATTLE);
        GiftRegistry.INSTANCE.assign(COAL, MINING, CHEAP);
        GiftRegistry.INSTANCE.assign(DIAMOND, MINING, PRETTY, RARE);
        GiftRegistry.INSTANCE.assign(IRON_INGOT, MINING);
        GiftRegistry.INSTANCE.assign(GOLD_INGOT, MINING);
        GiftRegistry.INSTANCE.assign(IRON_SWORD, BATTLE);
        GiftRegistry.INSTANCE.assign(WOODEN_SWORD, CHEAP, BATTLE);
        GiftRegistry.INSTANCE.assign(WOODEN_SHOVEL, MINING, TOOLS, CHEAP);
        GiftRegistry.INSTANCE.assign(WOODEN_PICKAXE, TOOLS, CHEAP);
        GiftRegistry.INSTANCE.assign(WOODEN_AXE, TOOLS, CHEAP);
        GiftRegistry.INSTANCE.assign(STONE_SWORD, CHEAP, BATTLE);
        GiftRegistry.INSTANCE.assign(STONE_SHOVEL, TOOLS, CHEAP);
        GiftRegistry.INSTANCE.assign(STONE_PICKAXE, MINING, TOOLS, CHEAP);
        GiftRegistry.INSTANCE.assign(STONE_AXE, TOOLS, CHEAP);
        GiftRegistry.INSTANCE.assign(DIAMOND_SWORD, RARE, BATTLE);
        GiftRegistry.INSTANCE.assign(DIAMOND_SHOVEL, TOOLS, RARE);
        GiftRegistry.INSTANCE.assign(DIAMOND_PICKAXE, MINING, TOOLS, RARE);
        GiftRegistry.INSTANCE.assign(DIAMOND_AXE, TOOLS, RARE);
        GiftRegistry.INSTANCE.assign(STICK, TOOLS, CHEAP);
        GiftRegistry.INSTANCE.assign(BOWL, CHEAP);
        GiftRegistry.INSTANCE.assign(MUSHROOM_STEW, NATURE, COOKING);
        GiftRegistry.INSTANCE.assign(GOLDEN_SWORD, BATTLE);
        GiftRegistry.INSTANCE.assign(GOLDEN_SHOVEL, TOOLS);
        GiftRegistry.INSTANCE.assign(GOLDEN_PICKAXE, MINING, TOOLS);
        GiftRegistry.INSTANCE.assign(GOLDEN_AXE, TOOLS);
        GiftRegistry.INSTANCE.assign(STRING, NATURE, CHEAP, KNITTING);
        GiftRegistry.INSTANCE.assign(FEATHER, CUTE, NATURE, ANIMALS, PRETTY, FARMING, GIRLY);
        GiftRegistry.INSTANCE.assign(GUNPOWDER, CHEAP, DANGER);
        GiftRegistry.INSTANCE.assign(WOODEN_HOE, TOOLS, CHEAP, FARMING);
        GiftRegistry.INSTANCE.assign(STONE_HOE, TOOLS, FARMING);
        GiftRegistry.INSTANCE.assign(IRON_HOE, TOOLS, FARMING);
        GiftRegistry.INSTANCE.assign(DIAMOND_HOE, TOOLS, FARMING);
        GiftRegistry.INSTANCE.assign(GOLDEN_HOE, TOOLS, FARMING);
        GiftRegistry.INSTANCE.assign(WHEAT_SEEDS, NATURE, CHEAP, FARMING);
        GiftRegistry.INSTANCE.assign(WHEAT, NATURE, COOKING, FARMING);
        GiftRegistry.INSTANCE.assign(BREAD, COOKING);
        GiftRegistry.INSTANCE.assign(LEATHER_HELMET, BATTLE);
        GiftRegistry.INSTANCE.assign(LEATHER_CHESTPLATE, BATTLE);
        GiftRegistry.INSTANCE.assign(LEATHER_LEGGINGS, BATTLE);
        GiftRegistry.INSTANCE.assign(LEATHER_BOOTS, BATTLE);
        GiftRegistry.INSTANCE.assign(CHAINMAIL_HELMET, BATTLE);
        GiftRegistry.INSTANCE.assign(CHAINMAIL_CHESTPLATE, BATTLE);
        GiftRegistry.INSTANCE.assign(CHAINMAIL_LEGGINGS, BATTLE);
        GiftRegistry.INSTANCE.assign(CHAINMAIL_BOOTS, BATTLE);
        GiftRegistry.INSTANCE.assign(IRON_HELMET, BATTLE);
        GiftRegistry.INSTANCE.assign(IRON_CHESTPLATE, BATTLE);
        GiftRegistry.INSTANCE.assign(IRON_LEGGINGS, BATTLE);
        GiftRegistry.INSTANCE.assign(IRON_BOOTS, BATTLE);
        GiftRegistry.INSTANCE.assign(DIAMOND_HELMET, PRETTY, RARE, BATTLE);
        GiftRegistry.INSTANCE.assign(DIAMOND_CHESTPLATE, PRETTY, RARE, BATTLE);
        GiftRegistry.INSTANCE.assign(DIAMOND_LEGGINGS, PRETTY, RARE, BATTLE);
        GiftRegistry.INSTANCE.assign(DIAMOND_BOOTS, PRETTY, RARE, BATTLE);
        GiftRegistry.INSTANCE.assign(GOLDEN_HELMET, BATTLE);
        GiftRegistry.INSTANCE.assign(GOLDEN_CHESTPLATE, BATTLE);
        GiftRegistry.INSTANCE.assign(GOLDEN_LEGGINGS, BATTLE);
        GiftRegistry.INSTANCE.assign(GOLDEN_BOOTS, BATTLE);
        GiftRegistry.INSTANCE.assign(FLINT, MINING, TOOLS, CHEAP);
        GiftRegistry.INSTANCE.assign(PORKCHOP, NATURE, COOKING, FARMING);
        GiftRegistry.INSTANCE.assign(COOKED_PORKCHOP, COOKING);
        GiftRegistry.INSTANCE.assign(PAINTING, PRETTY);
        GiftRegistry.INSTANCE.assign(GOLDEN_APPLE, RARE);
        GiftRegistry.INSTANCE.assign(SIGN, CHEAP, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(OAK_DOOR, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(SPRUCE_DOOR, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(BIRCH_DOOR, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(JUNGLE_DOOR, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(ACACIA_DOOR, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(DARK_OAK_DOOR, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(BUCKET, TOOLS);
        GiftRegistry.INSTANCE.assign(WATER_BUCKET, WATERY);
        GiftRegistry.INSTANCE.assign(LAVA_BUCKET, SCARY, DANGER);
        GiftRegistry.INSTANCE.assign(MINECART, MINING);
        GiftRegistry.INSTANCE.assign(SADDLE, CUTE, ANIMALS);
        GiftRegistry.INSTANCE.assign(IRON_DOOR, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(REDSTONE, MINING);
        GiftRegistry.INSTANCE.assign(SNOWBALL, CUTE);
        GiftRegistry.INSTANCE.assign(BOAT, WATERY);
        GiftRegistry.INSTANCE.assign(LEATHER, FARMING);
        GiftRegistry.INSTANCE.assign(MILK_BUCKET, ANIMALS, COOKING, FARMING);
        GiftRegistry.INSTANCE.assign(BRICK, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(CLAY_BALL, WATERY, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(REEDS, NATURE, FARMING);
        GiftRegistry.INSTANCE.assign(PAPER, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(BOOK, CHEAP);
        GiftRegistry.INSTANCE.assign(SLIME_BALL, SCARY, ANIMALS);
        GiftRegistry.INSTANCE.assign(CHEST_MINECART, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(FURNACE_MINECART, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(EGG, NATURE, ANIMALS, COOKING);
        GiftRegistry.INSTANCE.assign(COMPASS, TOOLS, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(FISHING_ROD, ANIMALS, WATERY);
        GiftRegistry.INSTANCE.assign(CLOCK, TOOLS, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(GLOWSTONE_DUST, PRETTY, GIRLY);
        GiftRegistry.INSTANCE.assign(FISH, NATURE, COOKING, WATERY);
        GiftRegistry.INSTANCE.assign(COOKED_FISH, COOKING, WATERY);
        GiftRegistry.INSTANCE.assign(DYE); //TODO: GiftRegistry.INSTANCE.assign THE VARIATIONS
        GiftRegistry.INSTANCE.assign(BONE, SCARY, DANGER);
        GiftRegistry.INSTANCE.assign(SUGAR, CUTE, COOKING, GIRLY);
        GiftRegistry.INSTANCE.assign(CAKE, CUTE, COOKING, GIRLY);
        GiftRegistry.INSTANCE.assign(BED, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(REPEATER, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(COOKIE, CUTE, COOKING);
        GiftRegistry.INSTANCE.assign(FILLED_MAP, TOOLS);
        GiftRegistry.INSTANCE.assign(SHEARS, TOOLS);
        GiftRegistry.INSTANCE.assign(MELON, NATURE, COOKING, FARMING);
        GiftRegistry.INSTANCE.assign(PUMPKIN_SEEDS, NATURE, FARMING);
        GiftRegistry.INSTANCE.assign(MELON_SEEDS, NATURE, FARMING);
        GiftRegistry.INSTANCE.assign(BEEF, NATURE, COOKING, FARMING);
        GiftRegistry.INSTANCE.assign(COOKED_BEEF, COOKING);
        GiftRegistry.INSTANCE.assign(CHICKEN, NATURE, COOKING, FARMING);
        GiftRegistry.INSTANCE.assign(COOKED_CHICKEN, COOKING);
        GiftRegistry.INSTANCE.assign(ROTTEN_FLESH, SCARY, DANGER);
        GiftRegistry.INSTANCE.assign(ENDER_PEARL, RARE, DANGER);
        GiftRegistry.INSTANCE.assign(BLAZE_ROD, DANGER);
        GiftRegistry.INSTANCE.assign(GHAST_TEAR, SCARY, RARE, DANGER);
        GiftRegistry.INSTANCE.assign(GOLD_NUGGET, MINING, DANGER);
        GiftRegistry.INSTANCE.assign(NETHER_WART, DANGER);
        GiftRegistry.INSTANCE.assign(POTIONITEM, WATERY, DANGER);
        GiftRegistry.INSTANCE.assign(GLASS_BOTTLE, COOKING, TOOLS);
        GiftRegistry.INSTANCE.assign(SPIDER_EYE, SCARY, DANGER);
        GiftRegistry.INSTANCE.assign(FERMENTED_SPIDER_EYE, SCARY, DANGER);
        GiftRegistry.INSTANCE.assign(BLAZE_POWDER, DANGER);
        GiftRegistry.INSTANCE.assign(MAGMA_CREAM, SCARY, DANGER);
        GiftRegistry.INSTANCE.assign(BREWING_STAND, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(CAULDRON, COOKING, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(ENDER_EYE, SCARY, RARE, DANGER);
        GiftRegistry.INSTANCE.assign(SPECKLED_MELON, PRETTY, DANGER);
        GiftRegistry.INSTANCE.assign(SPAWN_EGG, DANGER);
        GiftRegistry.INSTANCE.assign(EXPERIENCE_BOTTLE, PRETTY, RARE);
        GiftRegistry.INSTANCE.assign(FIRE_CHARGE, SCARY, DANGER);
        GiftRegistry.INSTANCE.assign(WRITABLE_BOOK, GIRLY);
        GiftRegistry.INSTANCE.assign(WRITTEN_BOOK, GIRLY);
        GiftRegistry.INSTANCE.assign(EMERALD, PRETTY, RARE);
        GiftRegistry.INSTANCE.assign(ITEM_FRAME, PRETTY);
        GiftRegistry.INSTANCE.assign(FLOWER_POT, CUTE, PRETTY);
        GiftRegistry.INSTANCE.assign(CARROT, NATURE, COOKING, FARMING);
        GiftRegistry.INSTANCE.assign(POTATO, NATURE, COOKING, FARMING);
        GiftRegistry.INSTANCE.assign(BAKED_POTATO, COOKING);
        GiftRegistry.INSTANCE.assign(POISONOUS_POTATO, SCARY, DANGER);
        GiftRegistry.INSTANCE.assign(MAP, TOOLS);
        GiftRegistry.INSTANCE.assign(GOLDEN_CARROT, PRETTY);
        GiftRegistry.INSTANCE.assign(SKULL, SCARY, RARE);
        GiftRegistry.INSTANCE.assign(CARROT_ON_A_STICK, ANIMALS);
        GiftRegistry.INSTANCE.assign(NETHER_STAR, PRETTY);
        GiftRegistry.INSTANCE.assign(PUMPKIN_PIE, COOKING);
        GiftRegistry.INSTANCE.assign(FIREWORKS, PRETTY, GIRLY);
        GiftRegistry.INSTANCE.assign(FIREWORK_CHARGE, DANGER);
        GiftRegistry.INSTANCE.assign(ENCHANTED_BOOK, RARE);
        GiftRegistry.INSTANCE.assign(COMPARATOR, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(NETHERBRICK, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(QUARTZ, MINING);
        GiftRegistry.INSTANCE.assign(TNT_MINECART, SCARY, DANGER);
        GiftRegistry.INSTANCE.assign(HOPPER_MINECART, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(IRON_HORSE_ARMOR, ANIMALS, GIRLY);
        GiftRegistry.INSTANCE.assign(GOLDEN_HORSE_ARMOR, ANIMALS, PRETTY, GIRLY);
        GiftRegistry.INSTANCE.assign(DIAMOND_HORSE_ARMOR, ANIMALS, PRETTY, RARE, GIRLY);
        GiftRegistry.INSTANCE.assign(LEAD, ANIMALS, FARMING);
        GiftRegistry.INSTANCE.assign(NAME_TAG, ANIMALS);
        GiftRegistry.INSTANCE.assign(COMMAND_BLOCK_MINECART, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(RECORD_13, RARE);
        GiftRegistry.INSTANCE.assign(RECORD_CAT, RARE);
        GiftRegistry.INSTANCE.assign(RECORD_BLOCKS, RARE);
        GiftRegistry.INSTANCE.assign(RECORD_CHIRP, RARE);
        GiftRegistry.INSTANCE.assign(RECORD_FAR, RARE);
        GiftRegistry.INSTANCE.assign(RECORD_MALL, RARE);
        GiftRegistry.INSTANCE.assign(RECORD_MELLOHI, RARE);
        GiftRegistry.INSTANCE.assign(RECORD_STAL, RARE);
        GiftRegistry.INSTANCE.assign(RECORD_STRAD, RARE);
        GiftRegistry.INSTANCE.assign(RECORD_WARD, RARE);
        GiftRegistry.INSTANCE.assign(RECORD_11, RARE);
        GiftRegistry.INSTANCE.assign(RECORD_WAIT, RARE);
        GiftRegistry.INSTANCE.assign(PRISMARINE_SHARD, PRETTY, WATERY);
        GiftRegistry.INSTANCE.assign(PRISMARINE_CRYSTALS, PRETTY, RARE, WATERY);
        GiftRegistry.INSTANCE.assign(BANNER, BATTLE, KNITTING);
        GiftRegistry.INSTANCE.assign(END_CRYSTAL, RARE, SCARY);
        GiftRegistry.INSTANCE.assign(ELYTRA, RARE, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(CHORUS_FRUIT, NATURE, SCARY, FARMING);
        GiftRegistry.INSTANCE.assign(CHORUS_FRUIT_POPPED, NATURE, SCARY, FARMING);
        GiftRegistry.INSTANCE.assign(BEETROOT_SEEDS, NATURE, CHEAP, FARMING);
        GiftRegistry.INSTANCE.assign(BEETROOT, NATURE, COOKING, FARMING);
        GiftRegistry.INSTANCE.assign(BEETROOT_SOUP, NATURE, COOKING);
    }
}