package joshie.harvest.npc.gift.init;

import joshie.harvest.npc.gift.GiftRegistry;

import static joshie.harvest.api.npc.gift.GiftCategory.*;
import static net.minecraft.init.Blocks.*;

public class HFGiftVanillaBlocks {
    public static void init() {
        GiftRegistry.INSTANCE.assign(STONE, MINING, CHEAP, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(GRASS, NATURE);
        GiftRegistry.INSTANCE.assign(DIRT, CHEAP);
        GiftRegistry.INSTANCE.assign(COBBLESTONE, MINING, CHEAP, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(PLANKS, CHEAP, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(SAPLING, NATURE, FARMING);
        GiftRegistry.INSTANCE.assign(SAND, CHEAP);
        GiftRegistry.INSTANCE.assign(GRAVEL, CHEAP);
        GiftRegistry.INSTANCE.assign(GOLD_ORE, MINING);
        GiftRegistry.INSTANCE.assign(IRON_ORE, MINING);
        GiftRegistry.INSTANCE.assign(COAL_ORE, MINING);
        GiftRegistry.INSTANCE.assign(LOG, CHEAP, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(LOG2, CHEAP, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(LEAVES, NATURE);
        GiftRegistry.INSTANCE.assign(LEAVES2, NATURE);
        GiftRegistry.INSTANCE.assign(SPONGE, NATURE, ANIMALS);
        GiftRegistry.INSTANCE.assign(GLASS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(LAPIS_ORE, MINING);
        GiftRegistry.INSTANCE.assign(LAPIS_BLOCK, PRETTY, CONSTRUCTION, RARE, GIRLY);
        GiftRegistry.INSTANCE.assign(DISPENSER, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(SANDSTONE, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(NOTEBLOCK, CUTE);
        GiftRegistry.INSTANCE.assign(GOLDEN_RAIL, MINING, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(DETECTOR_RAIL, MINING, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(STICKY_PISTON, CONSTRUCTION, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(WEB, SCARY, DANGER);
        GiftRegistry.INSTANCE.assign(TALLGRASS, NATURE);
        GiftRegistry.INSTANCE.assign(DEADBUSH, SCARY, NATURE, DANGER);
        GiftRegistry.INSTANCE.assign(PISTON, CONSTRUCTION, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(WOOL, FARMING, CONSTRUCTION, KNITTING);
        GiftRegistry.INSTANCE.assign(YELLOW_FLOWER, CUTE, NATURE, PRETTY, GIRLY);
        GiftRegistry.INSTANCE.assign(RED_FLOWER, CUTE, NATURE, PRETTY, GIRLY);
        GiftRegistry.INSTANCE.assign(BROWN_MUSHROOM, NATURE);
        GiftRegistry.INSTANCE.assign(RED_MUSHROOM, NATURE);
        GiftRegistry.INSTANCE.assign(GOLD_BLOCK, PRETTY, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(IRON_BLOCK, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(STONE_SLAB, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(BRICK_BLOCK, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(TNT, SCARY, MINING);
        GiftRegistry.INSTANCE.assign(BOOKSHELF, TECHNOLOGY, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(MOSSY_COBBLESTONE, MINING, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(OBSIDIAN, MINING, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(TORCH, MINING, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(MOB_SPAWNER, TECHNOLOGY, DANGER);
        GiftRegistry.INSTANCE.assign(OAK_STAIRS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(CHEST, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(DIAMOND_ORE, MINING);
        GiftRegistry.INSTANCE.assign(DIAMOND_BLOCK, PRETTY, CONSTRUCTION, RARE, GIRLY);
        GiftRegistry.INSTANCE.assign(CRAFTING_TABLE, CHEAP, CONSTRUCTION, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(FURNACE, CONSTRUCTION, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(LADDER, MINING, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(RAIL, MINING, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(STONE_STAIRS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(LEVER, CHEAP, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(STONE_PRESSURE_PLATE, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(WOODEN_PRESSURE_PLATE, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(REDSTONE_ORE, MINING);
        GiftRegistry.INSTANCE.assign(REDSTONE_TORCH, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(STONE_BUTTON, CHEAP, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(ICE, CUTE);
        GiftRegistry.INSTANCE.assign(SNOW, CUTE);
        GiftRegistry.INSTANCE.assign(CACTUS, NATURE, DANGER);
        GiftRegistry.INSTANCE.assign(CLAY, WATERY, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(JUKEBOX, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(OAK_FENCE, FARMING);
        GiftRegistry.INSTANCE.assign(SPRUCE_FENCE, FARMING);
        GiftRegistry.INSTANCE.assign(BIRCH_FENCE, FARMING);
        GiftRegistry.INSTANCE.assign(JUNGLE_FENCE, FARMING);
        GiftRegistry.INSTANCE.assign(ACACIA_FENCE, FARMING);
        GiftRegistry.INSTANCE.assign(DARK_OAK_FENCE, FARMING);
        GiftRegistry.INSTANCE.assign(PUMPKIN, NATURE, COOKING, FARMING);
        GiftRegistry.INSTANCE.assign(NETHERRACK, DANGER);
        GiftRegistry.INSTANCE.assign(SOUL_SAND, SCARY);
        GiftRegistry.INSTANCE.assign(GLOWSTONE, PRETTY);
        GiftRegistry.INSTANCE.assign(LIT_PUMPKIN, NATURE, PRETTY);
        GiftRegistry.INSTANCE.assign(TRAPDOOR, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(STONEBRICK, CHEAP, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(BROWN_MUSHROOM_BLOCK, NATURE);
        GiftRegistry.INSTANCE.assign(RED_MUSHROOM_BLOCK, NATURE);
        GiftRegistry.INSTANCE.assign(IRON_BARS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(GLASS_PANE, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(MELON_BLOCK, NATURE, COOKING, FARMING);
        GiftRegistry.INSTANCE.assign(VINE, NATURE);
        GiftRegistry.INSTANCE.assign(OAK_FENCE_GATE, FARMING, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(SPRUCE_FENCE_GATE, FARMING, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(BIRCH_FENCE_GATE, FARMING, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(JUNGLE_FENCE_GATE, FARMING, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(ACACIA_FENCE_GATE, FARMING, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(DARK_OAK_FENCE_GATE, FARMING, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(BRICK_STAIRS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(STONE_BRICK_STAIRS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(MYCELIUM, NATURE);
        GiftRegistry.INSTANCE.assign(WATERLILY, NATURE, WATERY, PRETTY, GIRLY);
        GiftRegistry.INSTANCE.assign(NETHER_BRICK, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(NETHER_BRICK_FENCE, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(NETHER_BRICK_STAIRS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(ENCHANTING_TABLE, RARE, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(END_STONE, DANGER);
        GiftRegistry.INSTANCE.assign(DRAGON_EGG, CUTE, PRETTY, RARE);
        GiftRegistry.INSTANCE.assign(REDSTONE_LAMP, CONSTRUCTION, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(WOODEN_SLAB, CHEAP, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(SANDSTONE_STAIRS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(EMERALD_ORE, MINING);
        GiftRegistry.INSTANCE.assign(ENDER_CHEST, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(TRIPWIRE_HOOK, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(EMERALD_BLOCK, PRETTY, CONSTRUCTION, RARE);
        GiftRegistry.INSTANCE.assign(SPRUCE_STAIRS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(BIRCH_STAIRS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(JUNGLE_STAIRS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(COMMAND_BLOCK, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(BEACON, PRETTY, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(COBBLESTONE_WALL, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(WOODEN_BUTTON, CHEAP);
        GiftRegistry.INSTANCE.assign(ANVIL, TOOLS, TECHNOLOGY, DANGER);
        GiftRegistry.INSTANCE.assign(TRAPPED_CHEST, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(LIGHT_WEIGHTED_PRESSURE_PLATE, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(HEAVY_WEIGHTED_PRESSURE_PLATE, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(DAYLIGHT_DETECTOR, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(REDSTONE_BLOCK, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(QUARTZ_ORE, MINING);
        GiftRegistry.INSTANCE.assign(HOPPER, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(QUARTZ_BLOCK, PRETTY, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(QUARTZ_STAIRS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(ACTIVATOR_RAIL, MINING, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(DROPPER, TECHNOLOGY);
        GiftRegistry.INSTANCE.assign(STAINED_HARDENED_CLAY, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(HAY_BLOCK, NATURE, ANIMALS, FARMING);
        GiftRegistry.INSTANCE.assign(CARPET, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(HARDENED_CLAY, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(COAL_BLOCK, MINING);
        GiftRegistry.INSTANCE.assign(PACKED_ICE, CHEAP);
        GiftRegistry.INSTANCE.assign(ACACIA_STAIRS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(DARK_OAK_STAIRS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(DOUBLE_PLANT, CUTE, NATURE, PRETTY);
        GiftRegistry.INSTANCE.assign(STAINED_GLASS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(STAINED_GLASS_PANE, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(PRISMARINE, WATERY);
        GiftRegistry.INSTANCE.assign(SEA_LANTERN, WATERY, PRETTY);
        GiftRegistry.INSTANCE.assign(STANDING_BANNER, BATTLE);
        GiftRegistry.INSTANCE.assign(RED_SANDSTONE, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(RED_SANDSTONE_STAIRS, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(PURPUR_BLOCK, CUTE, GIRLY, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(PURPUR_PILLAR, CUTE, GIRLY, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(PURPUR_SLAB, CUTE, GIRLY, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(PURPUR_STAIRS, CUTE, GIRLY, CONSTRUCTION);
        GiftRegistry.INSTANCE.assign(END_BRICKS, DANGER, CONSTRUCTION);
    }
}