package joshie.harvest.npc.gift.init;

import joshie.harvest.core.util.annotations.HFLoader;

import static joshie.harvest.api.npc.gift.GiftCategory.*;
import static net.minecraft.init.Items.*;

@HFLoader(priority = 0)
public class HFGiftsVanillaItems extends HFGiftsAbstract {
    public static void init() {
        assignGeneric(IRON_SHOVEL, TOOLS);
        assignGeneric(IRON_PICKAXE, MINING, TOOLS);
        assignGeneric(IRON_AXE, TOOLS);
        assignGeneric(FLINT_AND_STEEL, TOOLS, DANGER);
        assignGeneric(APPLE, NATURE, COOKING, FARMING);
        assignGeneric(BOW, TOOLS, BATTLE);
        assignGeneric(ARROW, TOOLS, BATTLE);
        assignGeneric(COAL, MINING, CHEAP);
        assignGeneric(DIAMOND, MINING, PRETTY, RARE);
        assignGeneric(IRON_INGOT, MINING);
        assignGeneric(GOLD_INGOT, MINING);
        assignGeneric(IRON_SWORD, BATTLE);
        assignGeneric(WOODEN_SWORD, CHEAP, BATTLE);
        assignGeneric(WOODEN_SHOVEL, MINING, TOOLS, CHEAP);
        assignGeneric(WOODEN_PICKAXE, TOOLS, CHEAP);
        assignGeneric(WOODEN_AXE, TOOLS, CHEAP);
        assignGeneric(STONE_SWORD, CHEAP, BATTLE);
        assignGeneric(STONE_SHOVEL, TOOLS, CHEAP);
        assignGeneric(STONE_PICKAXE, MINING, TOOLS, CHEAP);
        assignGeneric(STONE_AXE, TOOLS, CHEAP);
        assignGeneric(DIAMOND_SWORD, RARE, BATTLE);
        assignGeneric(DIAMOND_SHOVEL, TOOLS, RARE);
        assignGeneric(DIAMOND_PICKAXE, MINING, TOOLS, RARE);
        assignGeneric(DIAMOND_AXE, TOOLS, RARE);
        assignGeneric(STICK, TOOLS, CHEAP);
        assignGeneric(BOWL, CHEAP);
        assignGeneric(MUSHROOM_STEW, NATURE, COOKING);
        assignGeneric(GOLDEN_SWORD, BATTLE);
        assignGeneric(GOLDEN_SHOVEL, TOOLS);
        assignGeneric(GOLDEN_PICKAXE, MINING, TOOLS);
        assignGeneric(GOLDEN_AXE, TOOLS);
        assignGeneric(STRING, NATURE, CHEAP, KNITTING);
        assignGeneric(FEATHER, CUTE, NATURE, ANIMALS, PRETTY, FARMING, GIRLY);
        assignGeneric(GUNPOWDER, CHEAP, DANGER);
        assignGeneric(WOODEN_HOE, TOOLS, CHEAP, FARMING);
        assignGeneric(STONE_HOE, TOOLS, FARMING);
        assignGeneric(IRON_HOE, TOOLS, FARMING);
        assignGeneric(DIAMOND_HOE, TOOLS, FARMING);
        assignGeneric(GOLDEN_HOE, TOOLS, FARMING);
        assignGeneric(WHEAT_SEEDS, NATURE, CHEAP, FARMING);
        assignGeneric(WHEAT, NATURE, COOKING, FARMING);
        assignGeneric(BREAD, COOKING);
        assignGeneric(LEATHER_HELMET, BATTLE);
        assignGeneric(LEATHER_CHESTPLATE, BATTLE);
        assignGeneric(LEATHER_LEGGINGS, BATTLE);
        assignGeneric(LEATHER_BOOTS, BATTLE);
        assignGeneric(CHAINMAIL_HELMET, BATTLE);
        assignGeneric(CHAINMAIL_CHESTPLATE, BATTLE);
        assignGeneric(CHAINMAIL_LEGGINGS, BATTLE);
        assignGeneric(CHAINMAIL_BOOTS, BATTLE);
        assignGeneric(IRON_HELMET, BATTLE);
        assignGeneric(IRON_CHESTPLATE, BATTLE);
        assignGeneric(IRON_LEGGINGS, BATTLE);
        assignGeneric(IRON_BOOTS, BATTLE);
        assignGeneric(DIAMOND_HELMET, PRETTY, RARE, BATTLE);
        assignGeneric(DIAMOND_CHESTPLATE, PRETTY, RARE, BATTLE);
        assignGeneric(DIAMOND_LEGGINGS, PRETTY, RARE, BATTLE);
        assignGeneric(DIAMOND_BOOTS, PRETTY, RARE, BATTLE);
        assignGeneric(GOLDEN_HELMET, BATTLE);
        assignGeneric(GOLDEN_CHESTPLATE, BATTLE);
        assignGeneric(GOLDEN_LEGGINGS, BATTLE);
        assignGeneric(GOLDEN_BOOTS, BATTLE);
        assignGeneric(FLINT, MINING, TOOLS, CHEAP);
        assignGeneric(PORKCHOP, NATURE, COOKING, FARMING);
        assignGeneric(COOKED_PORKCHOP, COOKING);
        assignGeneric(PAINTING, PRETTY);
        assignGeneric(GOLDEN_APPLE, RARE);
        assignGeneric(SIGN, CHEAP, CONSTRUCTION);
        assignGeneric(OAK_DOOR, CONSTRUCTION);
        assignGeneric(SPRUCE_DOOR, CONSTRUCTION);
        assignGeneric(BIRCH_DOOR, CONSTRUCTION);
        assignGeneric(JUNGLE_DOOR, CONSTRUCTION);
        assignGeneric(ACACIA_DOOR, CONSTRUCTION);
        assignGeneric(DARK_OAK_DOOR, CONSTRUCTION);
        assignGeneric(BUCKET, TOOLS);
        assignGeneric(WATER_BUCKET, WATERY);
        assignGeneric(LAVA_BUCKET, SCARY, DANGER);
        assignGeneric(MINECART, MINING);
        assignGeneric(SADDLE, CUTE, ANIMALS);
        assignGeneric(IRON_DOOR, CONSTRUCTION);
        assignGeneric(REDSTONE, MINING);
        assignGeneric(SNOWBALL, CUTE);
        assignGeneric(BOAT, WATERY);
        assignGeneric(LEATHER, FARMING);
        assignGeneric(MILK_BUCKET, ANIMALS, COOKING, FARMING);
        assignGeneric(BRICK, CONSTRUCTION);
        assignGeneric(CLAY_BALL, WATERY, CONSTRUCTION);
        assignGeneric(REEDS, NATURE, FARMING);
        assignGeneric(PAPER, CONSTRUCTION);
        assignGeneric(BOOK, CHEAP);
        assignGeneric(SLIME_BALL, SCARY, ANIMALS);
        assignGeneric(CHEST_MINECART, TECHNOLOGY);
        assignGeneric(FURNACE_MINECART, TECHNOLOGY);
        assignGeneric(EGG, NATURE, ANIMALS, COOKING);
        assignGeneric(COMPASS, TOOLS, TECHNOLOGY);
        assignGeneric(FISHING_ROD, ANIMALS, WATERY);
        assignGeneric(CLOCK, TOOLS, TECHNOLOGY);
        assignGeneric(GLOWSTONE_DUST, PRETTY, GIRLY);
        assignGeneric(FISH, NATURE, COOKING, WATERY);
        assignGeneric(COOKED_FISH, COOKING, WATERY);
        assignGeneric(DYE); //TODO: assign THE VARIATIONS
        assignGeneric(BONE, SCARY, DANGER);
        assignGeneric(SUGAR, CUTE, COOKING, GIRLY);
        assignGeneric(CAKE, CUTE, COOKING, GIRLY);
        assignGeneric(BED, CONSTRUCTION);
        assignGeneric(REPEATER, TECHNOLOGY);
        assignGeneric(COOKIE, CUTE, COOKING);
        assignGeneric(FILLED_MAP, TOOLS);
        assignGeneric(SHEARS, TOOLS);
        assignGeneric(MELON, NATURE, COOKING, FARMING);
        assignGeneric(PUMPKIN_SEEDS, NATURE, FARMING);
        assignGeneric(MELON_SEEDS, NATURE, FARMING);
        assignGeneric(BEEF, NATURE, COOKING, FARMING);
        assignGeneric(COOKED_BEEF, COOKING);
        assignGeneric(CHICKEN, NATURE, COOKING, FARMING);
        assignGeneric(COOKED_CHICKEN, COOKING);
        assignGeneric(ROTTEN_FLESH, SCARY, DANGER);
        assignGeneric(ENDER_PEARL, RARE, DANGER);
        assignGeneric(BLAZE_ROD, DANGER);
        assignGeneric(GHAST_TEAR, SCARY, RARE, DANGER);
        assignGeneric(GOLD_NUGGET, MINING, DANGER);
        assignGeneric(NETHER_WART, DANGER);
        assignGeneric(POTIONITEM, WATERY, DANGER);
        assignGeneric(GLASS_BOTTLE, COOKING, TOOLS);
        assignGeneric(SPIDER_EYE, SCARY, DANGER);
        assignGeneric(FERMENTED_SPIDER_EYE, SCARY, DANGER);
        assignGeneric(BLAZE_POWDER, DANGER);
        assignGeneric(MAGMA_CREAM, SCARY, DANGER);
        assignGeneric(BREWING_STAND, TECHNOLOGY);
        assignGeneric(CAULDRON, COOKING, CONSTRUCTION);
        assignGeneric(ENDER_EYE, SCARY, RARE, DANGER);
        assignGeneric(SPECKLED_MELON, PRETTY, DANGER);
        assignGeneric(SPAWN_EGG, DANGER);
        assignGeneric(EXPERIENCE_BOTTLE, PRETTY, RARE);
        assignGeneric(FIRE_CHARGE, SCARY, DANGER);
        assignGeneric(WRITABLE_BOOK, GIRLY);
        assignGeneric(WRITTEN_BOOK, GIRLY);
        assignGeneric(EMERALD, PRETTY, RARE);
        assignGeneric(ITEM_FRAME, PRETTY);
        assignGeneric(FLOWER_POT, CUTE, PRETTY);
        assignGeneric(CARROT, NATURE, COOKING, FARMING);
        assignGeneric(POTATO, NATURE, COOKING, FARMING);
        assignGeneric(BAKED_POTATO, COOKING);
        assignGeneric(POISONOUS_POTATO, SCARY, DANGER);
        assignGeneric(MAP, TOOLS);
        assignGeneric(GOLDEN_CARROT, PRETTY);
        assignGeneric(SKULL, SCARY, RARE);
        assignGeneric(CARROT_ON_A_STICK, ANIMALS);
        assignGeneric(NETHER_STAR, PRETTY);
        assignGeneric(PUMPKIN_PIE, COOKING);
        assignGeneric(FIREWORKS, PRETTY, GIRLY);
        assignGeneric(FIREWORK_CHARGE, DANGER);
        assignGeneric(ENCHANTED_BOOK, RARE);
        assignGeneric(COMPARATOR, TECHNOLOGY);
        assignGeneric(NETHERBRICK, CONSTRUCTION);
        assignGeneric(QUARTZ, MINING);
        assignGeneric(TNT_MINECART, SCARY, DANGER);
        assignGeneric(HOPPER_MINECART, TECHNOLOGY);
        assignGeneric(IRON_HORSE_ARMOR, ANIMALS, GIRLY);
        assignGeneric(GOLDEN_HORSE_ARMOR, ANIMALS, PRETTY, GIRLY);
        assignGeneric(DIAMOND_HORSE_ARMOR, ANIMALS, PRETTY, RARE, GIRLY);
        assignGeneric(LEAD, ANIMALS, FARMING);
        assignGeneric(NAME_TAG, ANIMALS);
        assignGeneric(COMMAND_BLOCK_MINECART, TECHNOLOGY);
        assignGeneric(RECORD_13, RARE);
        assignGeneric(RECORD_CAT, RARE);
        assignGeneric(RECORD_BLOCKS, RARE);
        assignGeneric(RECORD_CHIRP, RARE);
        assignGeneric(RECORD_FAR, RARE);
        assignGeneric(RECORD_MALL, RARE);
        assignGeneric(RECORD_MELLOHI, RARE);
        assignGeneric(RECORD_STAL, RARE);
        assignGeneric(RECORD_STRAD, RARE);
        assignGeneric(RECORD_WARD, RARE);
        assignGeneric(RECORD_11, RARE);
        assignGeneric(RECORD_WAIT, RARE);
        assignGeneric(PRISMARINE_SHARD, PRETTY, WATERY);
        assignGeneric(PRISMARINE_CRYSTALS, PRETTY, RARE, WATERY);
        assignGeneric(BANNER, BATTLE, KNITTING);
        assignGeneric(END_CRYSTAL, RARE, SCARY);
        assignGeneric(ELYTRA, RARE, TECHNOLOGY);
        assignGeneric(CHORUS_FRUIT, NATURE, SCARY, FARMING);
        assignGeneric(CHORUS_FRUIT_POPPED, NATURE, SCARY, FARMING);
        assignGeneric(BEETROOT_SEEDS, NATURE, CHEAP, FARMING);
        assignGeneric(BEETROOT, NATURE, COOKING, FARMING);
        assignGeneric(BEETROOT_SOUP, NATURE, COOKING);
    }
}