package joshie.harvest.npc.gift.init;

import joshie.harvest.core.util.HFLoader;

import static joshie.harvest.api.npc.gift.GiftCategory.*;
import static net.minecraft.init.Blocks.*;

@HFLoader(priority = 0)
public class HFGiftsVanillaBlocks extends HFGiftsAbstract {
    public static void init() {
        assignGeneric(STONE, MINING, CHEAP, CONSTRUCTION);
        assignGeneric(GRASS, NATURE);
        assignGeneric(DIRT, CHEAP);
        assignGeneric(COBBLESTONE, MINING, CHEAP, CONSTRUCTION);
        assignGeneric(PLANKS, CHEAP, CONSTRUCTION);
        assignGeneric(SAPLING, NATURE, FARMING);
        assignGeneric(SAND, CHEAP);
        assignGeneric(GRAVEL, CHEAP);
        assignGeneric(GOLD_ORE, MINING);
        assignGeneric(IRON_ORE, MINING);
        assignGeneric(COAL_ORE, MINING);
        assignGeneric(LOG, CHEAP, CONSTRUCTION);
        assignGeneric(LOG2, CHEAP, CONSTRUCTION);
        assignGeneric(LEAVES, NATURE);
        assignGeneric(LEAVES2, NATURE);
        assignGeneric(SPONGE, NATURE, ANIMALS);
        assignGeneric(GLASS, CONSTRUCTION);
        assignGeneric(LAPIS_ORE, MINING);
        assignGeneric(LAPIS_BLOCK, PRETTY, CONSTRUCTION, RARE, GIRLY);
        assignGeneric(DISPENSER, TECHNOLOGY);
        assignGeneric(SANDSTONE, CONSTRUCTION);
        assignGeneric(NOTEBLOCK, CUTE);
        assignGeneric(GOLDEN_RAIL, MINING, TECHNOLOGY);
        assignGeneric(DETECTOR_RAIL, MINING, TECHNOLOGY);
        assignGeneric(STICKY_PISTON, CONSTRUCTION, TECHNOLOGY);
        assignGeneric(WEB, SCARY, DANGER);
        assignGeneric(TALLGRASS, NATURE);
        assignGeneric(DEADBUSH, SCARY, NATURE, DANGER);
        assignGeneric(PISTON, CONSTRUCTION, TECHNOLOGY);
        assignGeneric(WOOL, FARMING, CONSTRUCTION, KNITTING);
        assignGeneric(YELLOW_FLOWER, CUTE, NATURE, PRETTY, GIRLY);
        assignGeneric(RED_FLOWER, CUTE, NATURE, PRETTY, GIRLY);
        assignGeneric(BROWN_MUSHROOM, NATURE);
        assignGeneric(RED_MUSHROOM, NATURE);
        assignGeneric(GOLD_BLOCK, PRETTY, CONSTRUCTION);
        assignGeneric(IRON_BLOCK, CONSTRUCTION);
        assignGeneric(STONE_SLAB, CONSTRUCTION);
        assignGeneric(BRICK_BLOCK, CONSTRUCTION);
        assignGeneric(TNT, SCARY, MINING);
        assignGeneric(BOOKSHELF, TECHNOLOGY, CONSTRUCTION);
        assignGeneric(MOSSY_COBBLESTONE, MINING, CONSTRUCTION);
        assignGeneric(OBSIDIAN, MINING, CONSTRUCTION);
        assignGeneric(TORCH, MINING, CONSTRUCTION);
        assignGeneric(MOB_SPAWNER, TECHNOLOGY, DANGER);
        assignGeneric(OAK_STAIRS, CONSTRUCTION);
        assignGeneric(CHEST, CONSTRUCTION);
        assignGeneric(DIAMOND_ORE, MINING);
        assignGeneric(DIAMOND_BLOCK, PRETTY, CONSTRUCTION, RARE, GIRLY);
        assignGeneric(CRAFTING_TABLE, CHEAP, CONSTRUCTION, TECHNOLOGY);
        assignGeneric(FURNACE, CONSTRUCTION, TECHNOLOGY);
        assignGeneric(LADDER, MINING, CONSTRUCTION);
        assignGeneric(RAIL, MINING, TECHNOLOGY);
        assignGeneric(STONE_STAIRS, CONSTRUCTION);
        assignGeneric(LEVER, CHEAP, TECHNOLOGY);
        assignGeneric(STONE_PRESSURE_PLATE, TECHNOLOGY);
        assignGeneric(WOODEN_PRESSURE_PLATE, TECHNOLOGY);
        assignGeneric(REDSTONE_ORE, MINING);
        assignGeneric(REDSTONE_TORCH, TECHNOLOGY);
        assignGeneric(STONE_BUTTON, CHEAP, TECHNOLOGY);
        assignGeneric(ICE, CUTE);
        assignGeneric(SNOW, CUTE);
        assignGeneric(CACTUS, NATURE, DANGER);
        assignGeneric(CLAY, WATERY, CONSTRUCTION);
        assignGeneric(JUKEBOX, TECHNOLOGY);
        assignGeneric(OAK_FENCE, FARMING);
        assignGeneric(SPRUCE_FENCE, FARMING);
        assignGeneric(BIRCH_FENCE, FARMING);
        assignGeneric(JUNGLE_FENCE, FARMING);
        assignGeneric(ACACIA_FENCE, FARMING);
        assignGeneric(DARK_OAK_FENCE, FARMING);
        assignGeneric(PUMPKIN, NATURE, COOKING, FARMING);
        assignGeneric(NETHERRACK, DANGER);
        assignGeneric(SOUL_SAND, SCARY);
        assignGeneric(GLOWSTONE, PRETTY);
        assignGeneric(LIT_PUMPKIN, NATURE, PRETTY);
        assignGeneric(TRAPDOOR, TECHNOLOGY);
        assignGeneric(STONEBRICK, CHEAP, CONSTRUCTION);
        assignGeneric(BROWN_MUSHROOM_BLOCK, NATURE);
        assignGeneric(RED_MUSHROOM_BLOCK, NATURE);
        assignGeneric(IRON_BARS, CONSTRUCTION);
        assignGeneric(GLASS_PANE, CONSTRUCTION);
        assignGeneric(MELON_BLOCK, NATURE, COOKING, FARMING);
        assignGeneric(VINE, NATURE);
        assignGeneric(OAK_FENCE_GATE, FARMING, CONSTRUCTION);
        assignGeneric(SPRUCE_FENCE_GATE, FARMING, CONSTRUCTION);
        assignGeneric(BIRCH_FENCE_GATE, FARMING, CONSTRUCTION);
        assignGeneric(JUNGLE_FENCE_GATE, FARMING, CONSTRUCTION);
        assignGeneric(ACACIA_FENCE_GATE, FARMING, CONSTRUCTION);
        assignGeneric(DARK_OAK_FENCE_GATE, FARMING, CONSTRUCTION);
        assignGeneric(BRICK_STAIRS, CONSTRUCTION);
        assignGeneric(STONE_BRICK_STAIRS, CONSTRUCTION);
        assignGeneric(MYCELIUM, NATURE);
        assignGeneric(WATERLILY, NATURE, WATERY, PRETTY, GIRLY);
        assignGeneric(NETHER_BRICK, CONSTRUCTION);
        assignGeneric(NETHER_BRICK_FENCE, CONSTRUCTION);
        assignGeneric(NETHER_BRICK_STAIRS, CONSTRUCTION);
        assignGeneric(ENCHANTING_TABLE, RARE, TECHNOLOGY);
        assignGeneric(END_STONE, DANGER);
        assignGeneric(DRAGON_EGG, CUTE, PRETTY, RARE);
        assignGeneric(REDSTONE_LAMP, CONSTRUCTION, TECHNOLOGY);
        assignGeneric(WOODEN_SLAB, CHEAP, CONSTRUCTION);
        assignGeneric(SANDSTONE_STAIRS, CONSTRUCTION);
        assignGeneric(EMERALD_ORE, MINING);
        assignGeneric(ENDER_CHEST, CONSTRUCTION);
        assignGeneric(TRIPWIRE_HOOK, TECHNOLOGY);
        assignGeneric(EMERALD_BLOCK, PRETTY, CONSTRUCTION, RARE);
        assignGeneric(SPRUCE_STAIRS, CONSTRUCTION);
        assignGeneric(BIRCH_STAIRS, CONSTRUCTION);
        assignGeneric(JUNGLE_STAIRS, CONSTRUCTION);
        assignGeneric(COMMAND_BLOCK, TECHNOLOGY);
        assignGeneric(BEACON, PRETTY, TECHNOLOGY);
        assignGeneric(COBBLESTONE_WALL, CONSTRUCTION);
        assignGeneric(WOODEN_BUTTON, CHEAP);
        assignGeneric(ANVIL, TOOLS, TECHNOLOGY, DANGER);
        assignGeneric(TRAPPED_CHEST, TECHNOLOGY);
        assignGeneric(LIGHT_WEIGHTED_PRESSURE_PLATE, TECHNOLOGY);
        assignGeneric(HEAVY_WEIGHTED_PRESSURE_PLATE, TECHNOLOGY);
        assignGeneric(DAYLIGHT_DETECTOR, TECHNOLOGY);
        assignGeneric(REDSTONE_BLOCK, TECHNOLOGY);
        assignGeneric(QUARTZ_ORE, MINING);
        assignGeneric(HOPPER, TECHNOLOGY);
        assignGeneric(QUARTZ_BLOCK, PRETTY, CONSTRUCTION);
        assignGeneric(QUARTZ_STAIRS, CONSTRUCTION);
        assignGeneric(ACTIVATOR_RAIL, MINING, TECHNOLOGY);
        assignGeneric(DROPPER, TECHNOLOGY);
        assignGeneric(STAINED_HARDENED_CLAY, CONSTRUCTION);
        assignGeneric(HAY_BLOCK, NATURE, ANIMALS, FARMING);
        assignGeneric(CARPET, CONSTRUCTION);
        assignGeneric(HARDENED_CLAY, CONSTRUCTION);
        assignGeneric(COAL_BLOCK, MINING);
        assignGeneric(PACKED_ICE, CHEAP);
        assignGeneric(ACACIA_STAIRS, CONSTRUCTION);
        assignGeneric(DARK_OAK_STAIRS, CONSTRUCTION);
        assignGeneric(DOUBLE_PLANT, CUTE, NATURE, PRETTY);
        assignGeneric(STAINED_GLASS, CONSTRUCTION);
        assignGeneric(STAINED_GLASS_PANE, CONSTRUCTION);
        assignGeneric(PRISMARINE, WATERY);
        assignGeneric(SEA_LANTERN, WATERY, PRETTY);
        assignGeneric(STANDING_BANNER, BATTLE);
        assignGeneric(RED_SANDSTONE, CONSTRUCTION);
        assignGeneric(RED_SANDSTONE_STAIRS, CONSTRUCTION);
        assignGeneric(PURPUR_BLOCK, CUTE, GIRLY, CONSTRUCTION);
        assignGeneric(PURPUR_PILLAR, CUTE, GIRLY, CONSTRUCTION);
        assignGeneric(PURPUR_SLAB, CUTE, GIRLY, CONSTRUCTION);
        assignGeneric(PURPUR_STAIRS, CUTE, GIRLY, CONSTRUCTION);
        assignGeneric(END_BRICKS, DANGER, CONSTRUCTION);
    }
}