package joshie.harvest.npc.gift.init;

import static joshie.harvest.npc.gift.Gifts.Category.*;
import static joshie.harvest.npc.gift.Gifts.assign;
import static net.minecraft.init.Blocks.*;

public class HFGiftVanillaBlocks {
    public static void init() {
        assign(STONE, MINING, CHEAP, CONSTRUCTION);
        assign(GRASS, NATURE);
        assign(DIRT, CHEAP);
        assign(COBBLESTONE, MINING, CHEAP, CONSTRUCTION);
        assign(PLANKS, CHEAP, CONSTRUCTION);
        assign(SAPLING, NATURE, FARMING);
        assign(SAND, CHEAP);
        assign(GRAVEL, CHEAP);
        assign(GOLD_ORE, MINING);
        assign(IRON_ORE, MINING);
        assign(COAL_ORE, MINING);
        assign(LOG, CHEAP, CONSTRUCTION);
        assign(LOG2, CHEAP, CONSTRUCTION);
        assign(LEAVES, NATURE);
        assign(LEAVES2, NATURE);
        assign(SPONGE, NATURE, ANIMALS);
        assign(GLASS, CONSTRUCTION);
        assign(LAPIS_ORE, MINING);
        assign(LAPIS_BLOCK, PRETTY, CONSTRUCTION, RARE, GIRLY);
        assign(DISPENSER, TECHNOLOGY);
        assign(SANDSTONE, CONSTRUCTION);
        assign(NOTEBLOCK, CUTE);
        assign(GOLDEN_RAIL, MINING, TECHNOLOGY);
        assign(DETECTOR_RAIL, MINING, TECHNOLOGY);
        assign(STICKY_PISTON, CONSTRUCTION, TECHNOLOGY);
        assign(WEB, SCARY, DANGER);
        assign(TALLGRASS, NATURE);
        assign(DEADBUSH, SCARY, NATURE, DANGER);
        assign(PISTON, CONSTRUCTION, TECHNOLOGY);
        assign(WOOL, FARMING, CONSTRUCTION, KNITTING);
        assign(YELLOW_FLOWER, CUTE, NATURE, PRETTY, GIRLY);
        assign(RED_FLOWER, CUTE, NATURE, PRETTY, GIRLY);
        assign(BROWN_MUSHROOM, NATURE);
        assign(RED_MUSHROOM, NATURE);
        assign(GOLD_BLOCK, PRETTY, CONSTRUCTION);
        assign(IRON_BLOCK, CONSTRUCTION);
        assign(STONE_SLAB, CONSTRUCTION);
        assign(BRICK_BLOCK, CONSTRUCTION);
        assign(TNT, SCARY, MINING);
        assign(BOOKSHELF, TECHNOLOGY, CONSTRUCTION);
        assign(MOSSY_COBBLESTONE, MINING, CONSTRUCTION);
        assign(OBSIDIAN, MINING, CONSTRUCTION);
        assign(TORCH, MINING, CONSTRUCTION);
        assign(MOB_SPAWNER, TECHNOLOGY, DANGER);
        assign(OAK_STAIRS, CONSTRUCTION);
        assign(CHEST, CONSTRUCTION);
        assign(DIAMOND_ORE, MINING);
        assign(DIAMOND_BLOCK, PRETTY, CONSTRUCTION, RARE, GIRLY);
        assign(CRAFTING_TABLE, CHEAP, CONSTRUCTION, TECHNOLOGY);
        assign(FURNACE, CONSTRUCTION, TECHNOLOGY);
        assign(LADDER, MINING, CONSTRUCTION);
        assign(RAIL, MINING, TECHNOLOGY);
        assign(STONE_STAIRS, CONSTRUCTION);
        assign(LEVER, CHEAP, TECHNOLOGY);
        assign(STONE_PRESSURE_PLATE, TECHNOLOGY);
        assign(WOODEN_PRESSURE_PLATE, TECHNOLOGY);
        assign(REDSTONE_ORE, MINING);
        assign(REDSTONE_TORCH, TECHNOLOGY);
        assign(STONE_BUTTON, CHEAP, TECHNOLOGY);
        assign(ICE, CUTE);
        assign(SNOW, CUTE);
        assign(CACTUS, NATURE, DANGER);
        assign(CLAY, WATERY, CONSTRUCTION);
        assign(JUKEBOX, TECHNOLOGY);
        assign(OAK_FENCE, FARMING);
        assign(SPRUCE_FENCE, FARMING);
        assign(BIRCH_FENCE, FARMING);
        assign(JUNGLE_FENCE, FARMING);
        assign(ACACIA_FENCE, FARMING);
        assign(DARK_OAK_FENCE, FARMING);
        assign(PUMPKIN, NATURE, COOKING, FARMING);
        assign(NETHERRACK, DANGER);
        assign(SOUL_SAND, SCARY);
        assign(GLOWSTONE, PRETTY);
        assign(LIT_PUMPKIN, NATURE, PRETTY);
        assign(TRAPDOOR, TECHNOLOGY);
        assign(STONEBRICK, CHEAP, CONSTRUCTION);
        assign(BROWN_MUSHROOM_BLOCK, NATURE);
        assign(RED_MUSHROOM_BLOCK, NATURE);
        assign(IRON_BARS, CONSTRUCTION);
        assign(GLASS_PANE, CONSTRUCTION);
        assign(MELON_BLOCK, NATURE, COOKING, FARMING);
        assign(VINE, NATURE);
        assign(OAK_FENCE_GATE, FARMING, CONSTRUCTION);
        assign(SPRUCE_FENCE_GATE, FARMING, CONSTRUCTION);
        assign(BIRCH_FENCE_GATE, FARMING, CONSTRUCTION);
        assign(JUNGLE_FENCE_GATE, FARMING, CONSTRUCTION);
        assign(ACACIA_FENCE_GATE, FARMING, CONSTRUCTION);
        assign(DARK_OAK_FENCE_GATE, FARMING, CONSTRUCTION);
        assign(BRICK_STAIRS, CONSTRUCTION);
        assign(STONE_BRICK_STAIRS, CONSTRUCTION);
        assign(MYCELIUM, NATURE);
        assign(WATERLILY, NATURE, WATERY, PRETTY, GIRLY);
        assign(NETHER_BRICK, CONSTRUCTION);
        assign(NETHER_BRICK_FENCE, CONSTRUCTION);
        assign(NETHER_BRICK_STAIRS, CONSTRUCTION);
        assign(ENCHANTING_TABLE, RARE, TECHNOLOGY);
        assign(END_STONE, DANGER);
        assign(DRAGON_EGG, CUTE, PRETTY, RARE);
        assign(REDSTONE_LAMP, CONSTRUCTION, TECHNOLOGY);
        assign(WOODEN_SLAB, CHEAP, CONSTRUCTION);
        assign(SANDSTONE_STAIRS, CONSTRUCTION);
        assign(EMERALD_ORE, MINING);
        assign(ENDER_CHEST, CONSTRUCTION);
        assign(TRIPWIRE_HOOK, TECHNOLOGY);
        assign(EMERALD_BLOCK, PRETTY, CONSTRUCTION, RARE);
        assign(SPRUCE_STAIRS, CONSTRUCTION);
        assign(BIRCH_STAIRS, CONSTRUCTION);
        assign(JUNGLE_STAIRS, CONSTRUCTION);
        assign(COMMAND_BLOCK, TECHNOLOGY);
        assign(BEACON, PRETTY, TECHNOLOGY);
        assign(COBBLESTONE_WALL, CONSTRUCTION);
        assign(WOODEN_BUTTON, CHEAP);
        assign(ANVIL, TOOLS, TECHNOLOGY, DANGER);
        assign(TRAPPED_CHEST, TECHNOLOGY);
        assign(LIGHT_WEIGHTED_PRESSURE_PLATE, TECHNOLOGY);
        assign(HEAVY_WEIGHTED_PRESSURE_PLATE, TECHNOLOGY);
        assign(DAYLIGHT_DETECTOR, TECHNOLOGY);
        assign(REDSTONE_BLOCK, TECHNOLOGY);
        assign(QUARTZ_ORE, MINING);
        assign(HOPPER, TECHNOLOGY);
        assign(QUARTZ_BLOCK, PRETTY, CONSTRUCTION);
        assign(QUARTZ_STAIRS, CONSTRUCTION);
        assign(ACTIVATOR_RAIL, MINING, TECHNOLOGY);
        assign(DROPPER, TECHNOLOGY);
        assign(STAINED_HARDENED_CLAY, CONSTRUCTION);
        assign(HAY_BLOCK, NATURE, ANIMALS, FARMING);
        assign(CARPET, CONSTRUCTION);
        assign(HARDENED_CLAY, CONSTRUCTION);
        assign(COAL_BLOCK, MINING);
        assign(PACKED_ICE, CHEAP);
        assign(ACACIA_STAIRS, CONSTRUCTION);
        assign(DARK_OAK_STAIRS, CONSTRUCTION);
        assign(DOUBLE_PLANT, CUTE, NATURE, PRETTY);
        assign(STAINED_GLASS, CONSTRUCTION);
        assign(STAINED_GLASS_PANE, CONSTRUCTION);
    }
}