package joshie.harvestmoon.init.gifts;

import static joshie.harvestmoon.npc.gift.Gifts.assign;
import static joshie.harvestmoon.npc.gift.Gifts.Category.ANIMALS;
import static joshie.harvestmoon.npc.gift.Gifts.Category.CHEAP;
import static joshie.harvestmoon.npc.gift.Gifts.Category.CONSTRUCTION;
import static joshie.harvestmoon.npc.gift.Gifts.Category.COOKING;
import static joshie.harvestmoon.npc.gift.Gifts.Category.CUTE;
import static joshie.harvestmoon.npc.gift.Gifts.Category.DANGER;
import static joshie.harvestmoon.npc.gift.Gifts.Category.FARMING;
import static joshie.harvestmoon.npc.gift.Gifts.Category.GIRLY;
import static joshie.harvestmoon.npc.gift.Gifts.Category.KNITTING;
import static joshie.harvestmoon.npc.gift.Gifts.Category.MINING;
import static joshie.harvestmoon.npc.gift.Gifts.Category.NATURE;
import static joshie.harvestmoon.npc.gift.Gifts.Category.PRETTY;
import static joshie.harvestmoon.npc.gift.Gifts.Category.RARE;
import static joshie.harvestmoon.npc.gift.Gifts.Category.SCARY;
import static joshie.harvestmoon.npc.gift.Gifts.Category.TECHNOLOGY;
import static joshie.harvestmoon.npc.gift.Gifts.Category.TOOLS;
import static joshie.harvestmoon.npc.gift.Gifts.Category.WATER;
import static net.minecraft.init.Blocks.*;

public class HMGiftVanillaBlocks {
    public static void init() {
        assign(stone, MINING, CHEAP, CONSTRUCTION);
        assign(grass, NATURE);
        assign(dirt, CHEAP);
        assign(cobblestone, MINING, CHEAP, CONSTRUCTION);
        assign(planks, CHEAP, CONSTRUCTION);
        assign(sapling, NATURE, FARMING);
        assign(sand, CHEAP);
        assign(gravel, CHEAP);
        assign(gold_ore, MINING);
        assign(iron_ore, MINING);
        assign(coal_ore, MINING);
        assign(log, CHEAP, CONSTRUCTION);
        assign(log2, CHEAP, CONSTRUCTION);
        assign(leaves, NATURE);
        assign(leaves2, NATURE);
        assign(sponge, NATURE, ANIMALS);
        assign(glass, CONSTRUCTION);
        assign(lapis_ore, MINING);
        assign(lapis_block, PRETTY, CONSTRUCTION, RARE, GIRLY);
        assign(dispenser, TECHNOLOGY);
        assign(sandstone, CONSTRUCTION);
        assign(noteblock, CUTE);
        assign(golden_rail, MINING, TECHNOLOGY);
        assign(detector_rail, MINING, TECHNOLOGY);
        assign(sticky_piston, CONSTRUCTION, TECHNOLOGY);
        assign(web, SCARY, DANGER);
        assign(tallgrass, NATURE);
        assign(deadbush, SCARY, NATURE, DANGER);
        assign(piston, CONSTRUCTION, TECHNOLOGY);
        assign(wool, FARMING, CONSTRUCTION, KNITTING);
        assign(yellow_flower, CUTE, NATURE, PRETTY, GIRLY);
        assign(red_flower, CUTE, NATURE, PRETTY, GIRLY);
        assign(brown_mushroom, NATURE);
        assign(red_mushroom, NATURE);
        assign(gold_block, PRETTY, CONSTRUCTION);
        assign(iron_block, CONSTRUCTION);
        assign(stone_slab, CONSTRUCTION);
        assign(brick_block, CONSTRUCTION);
        assign(tnt, SCARY, MINING);
        assign(bookshelf, TECHNOLOGY, CONSTRUCTION);
        assign(mossy_cobblestone, MINING, CONSTRUCTION);
        assign(obsidian, MINING, CONSTRUCTION);
        assign(torch, MINING, CONSTRUCTION);
        assign(mob_spawner, TECHNOLOGY, DANGER);
        assign(oak_stairs, CONSTRUCTION);
        assign(chest, CONSTRUCTION);
        assign(diamond_ore, MINING);
        assign(diamond_block, PRETTY, CONSTRUCTION, RARE, GIRLY);
        assign(crafting_table, CHEAP, CONSTRUCTION, TECHNOLOGY);
        assign(furnace, CONSTRUCTION, TECHNOLOGY);
        assign(ladder, MINING, CONSTRUCTION);
        assign(rail, MINING, TECHNOLOGY);
        assign(stone_stairs, CONSTRUCTION);
        assign(lever, CHEAP, TECHNOLOGY);
        assign(stone_pressure_plate, TECHNOLOGY);
        assign(wooden_pressure_plate, TECHNOLOGY);
        assign(redstone_ore, MINING);
        assign(redstone_torch, TECHNOLOGY);
        assign(stone_button, CHEAP, TECHNOLOGY);
        assign(ice, CUTE);
        assign(snow, CUTE);
        assign(cactus, NATURE, DANGER);
        assign(clay, WATER, CONSTRUCTION);
        assign(jukebox, TECHNOLOGY);
        assign(fence, FARMING);
        assign(pumpkin, NATURE, COOKING, FARMING);
        assign(netherrack, DANGER);
        assign(soul_sand, SCARY);
        assign(glowstone, PRETTY);
        assign(lit_pumpkin, NATURE, PRETTY);
        assign(trapdoor, TECHNOLOGY);
        assign(stonebrick, CHEAP, CONSTRUCTION);
        assign(brown_mushroom_block, NATURE);
        assign(red_mushroom_block, NATURE);
        assign(iron_bars, CONSTRUCTION);
        assign(glass_pane, CONSTRUCTION);
        assign(melon_block, NATURE, COOKING, FARMING);
        assign(vine, NATURE);
        assign(fence_gate, FARMING, CONSTRUCTION);
        assign(brick_stairs, CONSTRUCTION);
        assign(stone_brick_stairs, CONSTRUCTION);
        assign(mycelium, NATURE);
        assign(waterlily, NATURE, WATER, PRETTY, GIRLY);
        assign(nether_brick, CONSTRUCTION);
        assign(nether_brick_fence, CONSTRUCTION);
        assign(nether_brick_stairs, CONSTRUCTION);
        assign(enchanting_table, RARE, TECHNOLOGY);
        assign(end_stone, DANGER);
        assign(dragon_egg, CUTE, PRETTY, RARE);
        assign(redstone_lamp, CONSTRUCTION, TECHNOLOGY);
        assign(wooden_slab, CHEAP, CONSTRUCTION);
        assign(sandstone_stairs, CONSTRUCTION);
        assign(emerald_ore, MINING);
        assign(ender_chest, CONSTRUCTION);
        assign(tripwire_hook, TECHNOLOGY);
        assign(emerald_block, PRETTY, CONSTRUCTION, RARE);
        assign(spruce_stairs, CONSTRUCTION);
        assign(birch_stairs, CONSTRUCTION);
        assign(jungle_stairs, CONSTRUCTION);
        assign(command_block, TECHNOLOGY);
        assign(beacon, PRETTY, TECHNOLOGY);
        assign(cobblestone_wall, CONSTRUCTION);
        assign(wooden_button, CHEAP);
        assign(anvil, TOOLS, TECHNOLOGY, DANGER);
        assign(trapped_chest, TECHNOLOGY);
        assign(light_weighted_pressure_plate, TECHNOLOGY);
        assign(heavy_weighted_pressure_plate, TECHNOLOGY);
        assign(daylight_detector, TECHNOLOGY);
        assign(redstone_block, TECHNOLOGY);
        assign(quartz_ore, MINING);
        assign(hopper, TECHNOLOGY);
        assign(quartz_block, PRETTY, CONSTRUCTION);
        assign(quartz_stairs, CONSTRUCTION);
        assign(activator_rail, MINING, TECHNOLOGY);
        assign(dropper, TECHNOLOGY);
        assign(stained_hardened_clay, CONSTRUCTION);
        assign(hay_block, NATURE, ANIMALS, FARMING);
        assign(carpet, CONSTRUCTION);
        assign(hardened_clay, CONSTRUCTION);
        assign(coal_block, MINING);
        assign(packed_ice, CHEAP);
        assign(acacia_stairs, CONSTRUCTION);
        assign(dark_oak_stairs, CONSTRUCTION);
        assign(double_plant, CUTE, NATURE, PRETTY);
        assign(stained_glass, CONSTRUCTION);
        assign(stained_glass_pane, CONSTRUCTION);
    }
}
