package joshie.harvestmoon.init.gifts;

import static joshie.harvestmoon.npc.gift.Gifts.assignWild;
import static joshie.harvestmoon.npc.gift.Gifts.Category.ANIMALS;
import static joshie.harvestmoon.npc.gift.Gifts.Category.BATTLE;
import static joshie.harvestmoon.npc.gift.Gifts.Category.CHEAP;
import static joshie.harvestmoon.npc.gift.Gifts.Category.CONSTRUCTION;
import static joshie.harvestmoon.npc.gift.Gifts.Category.COOKING;
import static joshie.harvestmoon.npc.gift.Gifts.Category.CUTE;
import static joshie.harvestmoon.npc.gift.Gifts.Category.DANGER;
import static joshie.harvestmoon.npc.gift.Gifts.Category.FARMING;
import static joshie.harvestmoon.npc.gift.Gifts.Category.GIRLY;
import static joshie.harvestmoon.npc.gift.Gifts.Category.KNITTING;
import static joshie.harvestmoon.npc.gift.Gifts.Category.MINING;
import static joshie.harvestmoon.npc.gift.Gifts.Category.NATURE;
import static joshie.harvestmoon.npc.gift.Gifts.Category.PRETTY;
import static joshie.harvestmoon.npc.gift.Gifts.Category.RARE;
import static joshie.harvestmoon.npc.gift.Gifts.Category.SCARY;
import static joshie.harvestmoon.npc.gift.Gifts.Category.TECHNOLOGY;
import static joshie.harvestmoon.npc.gift.Gifts.Category.TOOLS;
import static joshie.harvestmoon.npc.gift.Gifts.Category.WATER;
import static net.minecraft.init.Items.*;

public class HMGiftVanillaItems {
    public static void init() {
        assignWild(iron_shovel, TOOLS);
        assignWild(iron_pickaxe, MINING, TOOLS);
        assignWild(iron_axe, TOOLS);
        assignWild(flint_and_steel, TOOLS, DANGER);
        assignWild(apple, NATURE, COOKING, FARMING);
        assignWild(bow, TOOLS, BATTLE);
        assignWild(arrow, TOOLS, BATTLE);
        assignWild(coal, MINING, CHEAP);
        assignWild(diamond, MINING, PRETTY, RARE);
        assignWild(iron_ingot, MINING);
        assignWild(gold_ingot, MINING);
        assignWild(iron_sword, BATTLE);
        assignWild(wooden_sword, CHEAP, BATTLE);
        assignWild(wooden_shovel, MINING, TOOLS, CHEAP);
        assignWild(wooden_pickaxe, TOOLS, CHEAP);
        assignWild(wooden_axe, TOOLS, CHEAP);
        assignWild(stone_sword, CHEAP, BATTLE);
        assignWild(stone_shovel, TOOLS, CHEAP);
        assignWild(stone_pickaxe, MINING, TOOLS, CHEAP);
        assignWild(stone_axe, TOOLS, CHEAP);
        assignWild(diamond_sword, RARE, BATTLE);
        assignWild(diamond_shovel, TOOLS, RARE);
        assignWild(diamond_pickaxe, MINING, TOOLS, RARE);
        assignWild(diamond_axe, TOOLS, RARE);
        assignWild(stick, TOOLS, CHEAP);
        assignWild(bowl, CHEAP);
        assignWild(mushroom_stew, NATURE, COOKING);
        assignWild(golden_sword, BATTLE);
        assignWild(golden_shovel, TOOLS);
        assignWild(golden_pickaxe, MINING, TOOLS);
        assignWild(golden_axe, TOOLS);
        assignWild(string, NATURE, CHEAP, KNITTING);
        assignWild(feather, CUTE, NATURE, ANIMALS, PRETTY, FARMING, GIRLY);
        assignWild(gunpowder, CHEAP, DANGER);
        assignWild(wooden_hoe, TOOLS, CHEAP, FARMING);
        assignWild(stone_hoe, TOOLS, FARMING);
        assignWild(iron_hoe, TOOLS, FARMING);
        assignWild(diamond_hoe, TOOLS, FARMING);
        assignWild(golden_hoe, TOOLS, FARMING);
        assignWild(wheat_seeds, NATURE, CHEAP, FARMING);
        assignWild(wheat, NATURE, COOKING, FARMING);
        assignWild(bread, COOKING);
        assignWild(leather_helmet, BATTLE);
        assignWild(leather_chestplate, BATTLE);
        assignWild(leather_leggings, BATTLE);
        assignWild(leather_boots, BATTLE);
        assignWild(chainmail_helmet, BATTLE);
        assignWild(chainmail_chestplate, BATTLE);
        assignWild(chainmail_leggings, BATTLE);
        assignWild(chainmail_boots, BATTLE);
        assignWild(iron_helmet, BATTLE);
        assignWild(iron_chestplate, BATTLE);
        assignWild(iron_leggings, BATTLE);
        assignWild(iron_boots, BATTLE);
        assignWild(diamond_helmet, PRETTY, RARE, BATTLE);
        assignWild(diamond_chestplate, PRETTY, RARE, BATTLE);
        assignWild(diamond_leggings, PRETTY, RARE, BATTLE);
        assignWild(diamond_boots, PRETTY, RARE, BATTLE);
        assignWild(golden_helmet, BATTLE);
        assignWild(golden_chestplate, BATTLE);
        assignWild(golden_leggings, BATTLE);
        assignWild(golden_boots, BATTLE);
        assignWild(flint, MINING, TOOLS, CHEAP);
        assignWild(porkchop, NATURE, COOKING, FARMING);
        assignWild(cooked_porkchop, COOKING);
        assignWild(painting, PRETTY);
        assignWild(golden_apple, RARE);
        assignWild(sign, CHEAP, CONSTRUCTION);
        assignWild(wooden_door, CONSTRUCTION);
        assignWild(bucket, TOOLS);
        assignWild(water_bucket, WATER);
        assignWild(lava_bucket, SCARY, DANGER);
        assignWild(minecart, MINING);
        assignWild(saddle, CUTE, ANIMALS);
        assignWild(iron_door, CONSTRUCTION);
        assignWild(redstone, MINING);
        assignWild(snowball, CUTE);
        assignWild(boat, WATER);
        assignWild(leather, FARMING);
        assignWild(milk_bucket, ANIMALS, COOKING, FARMING);
        assignWild(brick, CONSTRUCTION);
        assignWild(clay_ball, WATER, CONSTRUCTION);
        assignWild(reeds, NATURE, FARMING);
        assignWild(paper, CONSTRUCTION);
        assignWild(book, CHEAP);
        assignWild(slime_ball, SCARY, ANIMALS);
        assignWild(chest_minecart, TECHNOLOGY);
        assignWild(furnace_minecart, TECHNOLOGY);
        assignWild(egg, NATURE, ANIMALS, COOKING);
        assignWild(compass, TOOLS, TECHNOLOGY);
        assignWild(fishing_rod, ANIMALS, WATER);
        assignWild(clock, TOOLS, TECHNOLOGY);
        assignWild(glowstone_dust, PRETTY, GIRLY);
        assignWild(fish, NATURE, COOKING, WATER);
        assignWild(cooked_fished, COOKING, WATER);
        assignWild(dye); //TODO: ASSIGN THE VARIATIONS
        assignWild(bone, SCARY, DANGER);
        assignWild(sugar, CUTE, COOKING, GIRLY);
        assignWild(cake, CUTE, COOKING, GIRLY);
        assignWild(bed, CONSTRUCTION);
        assignWild(repeater, TECHNOLOGY);
        assignWild(cookie, CUTE, COOKING);
        assignWild(filled_map, TOOLS);
        assignWild(shears, TOOLS);
        assignWild(melon, NATURE, COOKING, FARMING);
        assignWild(pumpkin_seeds, NATURE, FARMING);
        assignWild(melon_seeds, NATURE, FARMING);
        assignWild(beef, NATURE, COOKING, FARMING);
        assignWild(cooked_beef, COOKING);
        assignWild(chicken, NATURE, COOKING, FARMING);
        assignWild(cooked_chicken, COOKING);
        assignWild(rotten_flesh, SCARY, DANGER);
        assignWild(ender_pearl, RARE, DANGER);
        assignWild(blaze_rod, DANGER);
        assignWild(ghast_tear, SCARY, RARE, DANGER);
        assignWild(gold_nugget, MINING, DANGER);
        assignWild(nether_wart, DANGER);
        assignWild(potionitem, WATER, DANGER);
        assignWild(glass_bottle, COOKING, TOOLS);
        assignWild(spider_eye, SCARY, DANGER);
        assignWild(fermented_spider_eye, SCARY, DANGER);
        assignWild(blaze_powder, DANGER);
        assignWild(magma_cream, SCARY, DANGER);
        assignWild(brewing_stand, TECHNOLOGY);
        assignWild(cauldron, COOKING, CONSTRUCTION);
        assignWild(ender_eye, SCARY, RARE, DANGER);
        assignWild(speckled_melon, PRETTY, DANGER);
        assignWild(spawn_egg, DANGER);
        assignWild(experience_bottle, PRETTY, RARE);
        assignWild(fire_charge, SCARY, DANGER);
        assignWild(writable_book, GIRLY);
        assignWild(written_book, GIRLY);
        assignWild(emerald, PRETTY, RARE);
        assignWild(item_frame, PRETTY);
        assignWild(flower_pot, CUTE, PRETTY);
        assignWild(carrot, NATURE, COOKING, FARMING);
        assignWild(potato, NATURE, COOKING, FARMING);
        assignWild(baked_potato, COOKING);
        assignWild(poisonous_potato, SCARY, DANGER);
        assignWild(map, TOOLS);
        assignWild(golden_carrot, PRETTY);
        assignWild(skull, SCARY, RARE);
        assignWild(carrot_on_a_stick, ANIMALS);
        assignWild(nether_star, PRETTY);
        assignWild(pumpkin_pie, COOKING);
        assignWild(fireworks, PRETTY, GIRLY);
        assignWild(firework_charge, DANGER);
        assignWild(enchanted_book, RARE);
        assignWild(comparator, TECHNOLOGY);
        assignWild(netherbrick, CONSTRUCTION);
        assignWild(quartz, MINING);
        assignWild(tnt_minecart, SCARY, DANGER);
        assignWild(hopper_minecart, TECHNOLOGY);
        assignWild(iron_horse_armor, ANIMALS, GIRLY);
        assignWild(golden_horse_armor, ANIMALS, PRETTY, GIRLY);
        assignWild(diamond_horse_armor, ANIMALS, PRETTY, RARE, GIRLY);
        assignWild(lead, ANIMALS, FARMING);
        assignWild(name_tag, ANIMALS);
        assignWild(command_block_minecart, TECHNOLOGY);
        assignWild(record_13, RARE);
        assignWild(record_cat, RARE);
        assignWild(record_blocks, RARE);
        assignWild(record_chirp, RARE);
        assignWild(record_far, RARE);
        assignWild(record_mall, RARE);
        assignWild(record_mellohi, RARE);
        assignWild(record_stal, RARE);
        assignWild(record_strad, RARE);
        assignWild(record_ward, RARE);
        assignWild(record_11, RARE);
        assignWild(record_wait, RARE);
    }
}
