package joshie.harvestmoon.init;

import static joshie.harvestmoon.npc.gift.Gifts.assignWild;
import static joshie.harvestmoon.npc.gift.Gifts.Category.ANIMALS;
import static joshie.harvestmoon.npc.gift.Gifts.Category.CHEAP;
import static joshie.harvestmoon.npc.gift.Gifts.Category.CONSTRUCTION;
import static joshie.harvestmoon.npc.gift.Gifts.Category.COOKING;
import static joshie.harvestmoon.npc.gift.Gifts.Category.CUTE;
import static joshie.harvestmoon.npc.gift.Gifts.Category.DANGER;
import static joshie.harvestmoon.npc.gift.Gifts.Category.FARMING;
import static joshie.harvestmoon.npc.gift.Gifts.Category.GIRLY;
import static joshie.harvestmoon.npc.gift.Gifts.Category.KNITTING;
import static joshie.harvestmoon.npc.gift.Gifts.Category.MINING;
import static joshie.harvestmoon.npc.gift.Gifts.Category.NATURE;
import static joshie.harvestmoon.npc.gift.Gifts.Category.PRETTY;
import static joshie.harvestmoon.npc.gift.Gifts.Category.RARE;
import static joshie.harvestmoon.npc.gift.Gifts.Category.SCARY;
import static joshie.harvestmoon.npc.gift.Gifts.Category.TECHNOLOGY;
import static joshie.harvestmoon.npc.gift.Gifts.Category.TOOLS;
import static joshie.harvestmoon.npc.gift.Gifts.Category.WATER;
import static net.minecraft.init.Blocks.*;
public class HMGiftBlocks {
    public static void init() {
        /** assignWild all them blocks D= **/
        assignWild(stone, MINING, CHEAP, CONSTRUCTION);
        assignWild(grass, NATURE);
        assignWild(dirt, CHEAP);
        assignWild(cobblestone, MINING, CHEAP, CONSTRUCTION);
        assignWild(planks, CHEAP, CONSTRUCTION);
        assignWild(sapling, NATURE, FARMING);
        assignWild(sand, CHEAP);
        assignWild(gravel, CHEAP);
        assignWild(gold_ore, MINING);
        assignWild(iron_ore, MINING);
        assignWild(coal_ore, MINING);
        assignWild(log, CHEAP, CONSTRUCTION);
        assignWild(log2, CHEAP, CONSTRUCTION);
        assignWild(leaves, NATURE);
        assignWild(leaves2, NATURE);
        assignWild(sponge, NATURE, ANIMALS);
        assignWild(glass, CONSTRUCTION);
        assignWild(lapis_ore, MINING);
        assignWild(lapis_block, PRETTY, CONSTRUCTION, RARE, GIRLY);
        assignWild(dispenser, TECHNOLOGY);
        assignWild(sandstone, CONSTRUCTION);
        assignWild(noteblock, CUTE);
        assignWild(golden_rail, MINING, TECHNOLOGY);
        assignWild(detector_rail, MINING, TECHNOLOGY);
        assignWild(sticky_piston, CONSTRUCTION, TECHNOLOGY);
        assignWild(web, SCARY, DANGER);
        assignWild(tallgrass, NATURE);
        assignWild(deadbush, SCARY, NATURE, DANGER);
        assignWild(piston, CONSTRUCTION, TECHNOLOGY);
        assignWild(wool, FARMING, CONSTRUCTION, KNITTING);
        assignWild(yellow_flower, CUTE, NATURE, PRETTY, GIRLY);
        assignWild(red_flower, CUTE, NATURE, PRETTY, GIRLY);
        assignWild(brown_mushroom, NATURE);
        assignWild(red_mushroom, NATURE);
        assignWild(gold_block, PRETTY, CONSTRUCTION);
        assignWild(iron_block, CONSTRUCTION);
        assignWild(stone_slab, CONSTRUCTION);
        assignWild(brick_block, CONSTRUCTION);
        assignWild(tnt, SCARY, MINING);
        assignWild(bookshelf, TECHNOLOGY, CONSTRUCTION);
        assignWild(mossy_cobblestone, MINING, CONSTRUCTION);
        assignWild(obsidian, MINING, CONSTRUCTION);
        assignWild(torch, MINING, CONSTRUCTION);
        assignWild(mob_spawner, TECHNOLOGY, DANGER);
        assignWild(oak_stairs, CONSTRUCTION);
        assignWild(chest, CONSTRUCTION);
        assignWild(diamond_ore, MINING);
        assignWild(diamond_block, PRETTY, CONSTRUCTION, RARE, GIRLY);
        assignWild(crafting_table, CHEAP, CONSTRUCTION, TECHNOLOGY);
        assignWild(furnace, CONSTRUCTION, TECHNOLOGY);
        assignWild(ladder, MINING, CONSTRUCTION);
        assignWild(rail, MINING, TECHNOLOGY);
        assignWild(stone_stairs, CONSTRUCTION);
        assignWild(lever, CHEAP, TECHNOLOGY);
        assignWild(stone_pressure_plate, TECHNOLOGY);
        assignWild(wooden_pressure_plate, TECHNOLOGY);
        assignWild(redstone_ore, MINING);
        assignWild(redstone_torch, TECHNOLOGY);
        assignWild(stone_button, CHEAP, TECHNOLOGY);
        assignWild(ice, CUTE);
        assignWild(snow, CUTE);
        assignWild(cactus, NATURE, DANGER);
        assignWild(clay, WATER, CONSTRUCTION);
        assignWild(jukebox, TECHNOLOGY);
        assignWild(fence, FARMING);
        assignWild(pumpkin, NATURE, COOKING, FARMING);
        assignWild(netherrack, DANGER);
        assignWild(soul_sand, SCARY);
        assignWild(glowstone, PRETTY);
        assignWild(lit_pumpkin, NATURE, PRETTY);
        assignWild(trapdoor, TECHNOLOGY);
        assignWild(stonebrick, CHEAP, CONSTRUCTION);
        assignWild(brown_mushroom_block, NATURE);
        assignWild(red_mushroom_block, NATURE);
        assignWild(iron_bars, CONSTRUCTION);
        assignWild(glass_pane, CONSTRUCTION);
        assignWild(melon_block, NATURE, COOKING, FARMING);
        assignWild(vine, NATURE);
        assignWild(fence_gate, FARMING, CONSTRUCTION);
        assignWild(brick_stairs, CONSTRUCTION);
        assignWild(stone_brick_stairs, CONSTRUCTION);
        assignWild(mycelium, NATURE);
        assignWild(waterlily, NATURE, WATER, PRETTY, GIRLY);
        assignWild(nether_brick, CONSTRUCTION);
        assignWild(nether_brick_fence, CONSTRUCTION);
        assignWild(nether_brick_stairs, CONSTRUCTION);
        assignWild(enchanting_table, RARE, TECHNOLOGY);
        assignWild(end_stone, DANGER);
        assignWild(dragon_egg, CUTE, PRETTY, RARE);
        assignWild(redstone_lamp, CONSTRUCTION, TECHNOLOGY);
        assignWild(wooden_slab, CHEAP, CONSTRUCTION);
        assignWild(sandstone_stairs, CONSTRUCTION);
        assignWild(emerald_ore, MINING);
        assignWild(ender_chest, CONSTRUCTION);
        assignWild(tripwire_hook, TECHNOLOGY);
        assignWild(emerald_block, PRETTY, CONSTRUCTION, RARE);
        assignWild(spruce_stairs, CONSTRUCTION);
        assignWild(birch_stairs, CONSTRUCTION);
        assignWild(jungle_stairs, CONSTRUCTION);
        assignWild(command_block, TECHNOLOGY);
        assignWild(beacon, PRETTY, TECHNOLOGY);
        assignWild(cobblestone_wall, CONSTRUCTION);
        assignWild(wooden_button, CHEAP);
        assignWild(anvil, TOOLS, TECHNOLOGY, DANGER);
        assignWild(trapped_chest, TECHNOLOGY);
        assignWild(light_weighted_pressure_plate, TECHNOLOGY);
        assignWild(heavy_weighted_pressure_plate, TECHNOLOGY);
        assignWild(daylight_detector, TECHNOLOGY);
        assignWild(redstone_block, TECHNOLOGY);
        assignWild(quartz_ore, MINING);
        assignWild(hopper, TECHNOLOGY);
        assignWild(quartz_block, PRETTY, CONSTRUCTION);
        assignWild(quartz_stairs, CONSTRUCTION);
        assignWild(activator_rail, MINING, TECHNOLOGY);
        assignWild(dropper, TECHNOLOGY);
        assignWild(stained_hardened_clay, CONSTRUCTION);
        assignWild(hay_block, NATURE, ANIMALS, FARMING);
        assignWild(carpet, CONSTRUCTION);
        assignWild(hardened_clay, CONSTRUCTION);
        assignWild(coal_block, MINING);
        assignWild(packed_ice, CHEAP);
        assignWild(acacia_stairs, CONSTRUCTION);
        assignWild(dark_oak_stairs, CONSTRUCTION);
        assignWild(double_plant, CUTE, NATURE, PRETTY);
        assignWild(stained_glass, CONSTRUCTION);
        assignWild(stained_glass_pane, CONSTRUCTION);
    }
}
