package joshie.harvest.api.gathering;

import joshie.harvest.api.calendar.Season;
import net.minecraft.block.state.IBlockState;
import net.minecraft.world.World;

import javax.annotation.Nullable;

/** This is for registering blocks to be generated by the gathering system **/
public interface IGatheringRegistry {
    /** Register a block state to be generated in a specific season
     * @param state the block state to generate
     * @param weight weight for this to generate
     * @param seasons the season this should generate in,
     *                leave this blank if it should generate
     *                in every single season. **/
    void registerGathering(IBlockState state, double weight, Season... seasons);

    /** Returns a random block state for this season
     * @param world the world object
     * @param season the current season
     * @return a block state */
    @Nullable
    IBlockState getRandomStateForSeason(World world, @Nullable Season season);
}
