package joshie.harvest.buildings;

import joshie.harvest.api.buildings.IBuilding;
import joshie.harvest.buildings.loader.HFBuildings;
import joshie.harvest.buildings.placeable.Placeable;
import joshie.harvest.buildings.placeable.blocks.*;
import joshie.harvest.buildings.placeable.entities.PlaceableItemFrame;
import joshie.harvest.buildings.placeable.entities.PlaceableNPC;
import joshie.harvest.core.handlers.HFTrackers;
import joshie.harvest.core.lib.LootStrings;
import joshie.harvest.player.town.TownData;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumFacing;
import net.minecraft.world.World;

import java.util.List;

public class BuildingBlacksmith extends BuildingAbstract {
    public BuildingBlacksmith() {
        super("blacksmith");
    }

    @Override
    public int getOffsetY() {
        return -2;
    }

    @Override
    public long getCost() {
        return 3500L;
    }

    @Override
    public int getWoodCount() {
        return 32;
    }

    @Override
    public int getStoneCount() {
        return 244;
    }

    @Override
    public boolean canBuy(World world, EntityPlayer player) {
        return HFTrackers.getPlayerTracker(player).getTown().hasBuilding(HFBuildings.supermarket);
    }

    @Override
    public String[] getRequirements() {
        return new String[] { "supermarket" };
    }

    @Override
    public IBuilding addBlocks(List<Placeable> list) {
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 2, 0, 10));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 5, 0, 10));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 1, 1, 1));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 1, 1, 5));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 1, 1, 7));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 1, 1, 8));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 1, 1, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 1, 1, 10));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 2, 1, 0));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 2, 1, 1));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 2, 1, 2));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 2, 1, 3));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 2, 1, 4));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 2, 1, 5));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 2, 1, 6));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 2, 1, 7));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 2, 1, 8));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 2, 1, 9));
        list.add(new PlaceableBlock(Blocks.LAVA, 0, 2, 1, 10));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 2, 1, 11));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 3, 1, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 3, 1, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 3, 1, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 3, 1, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 3, 1, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 3, 1, 6));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 3, 1, 7));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 3, 1, 8));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 3, 1, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 3, 1, 10));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 3, 1, 11));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 4, 1, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 1, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 1, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 1, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 1, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 1, 6));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 4, 1, 7));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 4, 1, 8));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 4, 1, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 4, 1, 10));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 4, 1, 11));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 5, 1, 0));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 5, 1, 1));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 5, 1, 2));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 5, 1, 3));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 5, 1, 4));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 5, 1, 5));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 5, 1, 6));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 5, 1, 7));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 5, 1, 8));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 5, 1, 9));
        list.add(new PlaceableBlock(Blocks.LAVA, 0, 5, 1, 10));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 5, 1, 11));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 6, 1, 1));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 6, 1, 5));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 6, 1, 7));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 6, 1, 8));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 6, 1, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 6, 1, 10));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 1, 2, 1));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 1, 2, 5));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 1, 2, 7));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 1, 1, 2, 8));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 1, 1, 2, 9));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 1, 2, 10));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 2, 2, 0));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 2, 2, 1));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 2, 2, 2));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 2, 2, 3));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 2, 2, 4));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 2, 2, 5));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 2, 2, 6));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 1, 2, 2, 7));
        list.add(new PlaceableDecorative(Blocks.ANVIL, 8, 2, 2, 8));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 2, 2, 9));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 3, 2, 2, 11));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 2, 3, 2, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 1, 3, 2, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 2, 3));
        list.add(new PlaceableItemFrame(null, 0, EnumFacing.SOUTH, 3, 2, 3));
        list.add(new PlaceableNPC(TownData.BLACKSMITH_FRONT, "", 3, 2, 4));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 2, 4));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 5, 3, 2, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 15, 3, 2, 6));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 2, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 2, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 2, 9));
        list.add(new PlaceableFurnace(Blocks.LIT_FURNACE, 2, 3, 2, 10));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 2, 3, 2, 11));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 2, 4, 2, 1));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 4, 2, 2));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 4, 2, 6));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 2, 7));
        list.add(new PlaceableNPC(TownData.DANIEL, "daniel", 4, 2, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 2, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 2, 9));
        list.add(new PlaceableFurnace(Blocks.LIT_FURNACE, 2, 4, 2, 10));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 2, 4, 2, 11));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 5, 2, 0));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 5, 2, 1));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 1, 5, 2, 2));
        list.add(new PlaceableDecorative(Blocks.OAK_DOOR, 0, 5, 2, 3));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 1, 5, 2, 4));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 5, 2, 5));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 1, 5, 2, 6));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 5, 2, 7));
        list.add(new PlaceableChest(Blocks.CHEST, 4, 5, 2, 8, LootStrings.BLACKSMITH_CHEST));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 5, 2, 9));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 3, 5, 2, 11));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 6, 2, 1));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 6, 2, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 6, 2, 3));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 6, 2, 4));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 6, 2, 5));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 1, 6, 2, 7));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 6, 2, 8));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 6, 2, 9));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 1, 6, 2, 10));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 1, 3, 1));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 1, 3, 5));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 1, 3, 7));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 3, 1, 3, 8));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 2, 1, 3, 9));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 1, 3, 10));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 2, 3, 0));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 2, 3, 1));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 3, 2, 3, 2));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 2, 3, 3));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 2, 2, 3, 4));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 2, 3, 5));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 4, 2, 3, 6));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 5, 2, 3, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 2, 3, 8));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 2, 3, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 2, 3, 10));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 2, 3, 11));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 1, 3, 3, 1));
        list.add(new PlaceableFlowerPot(Blocks.FLOWER_POT, 4, 3, 3, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 15, 3, 3, 6));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 3, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 3, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 3, 9));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 3, 3, 10));
        list.add(new PlaceableItemFrame(new ItemStack(Items.IRON_SWORD, 1, 0), 0, EnumFacing.NORTH, 3, 3, 10, LootStrings.BLACKSMITH_FRAME));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 1, 3, 3, 11));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 4, 3, 1));
        list.add(new PlaceableBlock(Blocks.CARPET, 12, 4, 3, 2));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 4, 3, 6));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 3, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 3, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 3, 9));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 4, 3, 10));
        list.add(new PlaceableItemFrame(new ItemStack(Items.IRON_SWORD, 1, 0), 0, EnumFacing.NORTH, 4, 3, 10, LootStrings.BLACKSMITH_FRAME));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 4, 3, 11));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 5, 3, 0));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 5, 3, 1));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 5, 3, 2));
        list.add(new PlaceableDecorative(Blocks.OAK_DOOR, 8, 5, 3, 3));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 5, 3, 4));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 5, 3, 5));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 5, 5, 3, 6));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 4, 5, 3, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 5, 3, 8));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 5, 3, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 5, 3, 10));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 5, 3, 11));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 6, 3, 1));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 6, 3, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 6, 3, 3));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 6, 3, 4));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 6, 3, 5));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 6, 3, 7));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 3, 6, 3, 8));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 2, 6, 3, 9));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 6, 3, 10));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 1, 4, 0));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 1, 4, 1));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 1, 4, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 1, 4, 6));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 3, 1, 4, 8));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 2, 1, 4, 9));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 2, 4, 0));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 2, 4, 1));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 7, 2, 4, 2));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 8, 2, 4, 3));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 6, 2, 4, 4));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 2, 4, 5));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 2, 4, 6));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 2, 4, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 2, 4, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 2, 4, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 2, 4, 10));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 5, 3, 4, 1));
        list.add(new PlaceableDecorative(Blocks.TORCH, 4, 3, 4, 5));
        list.add(new PlaceableItemFrame(new ItemStack(Blocks.TRAPDOOR, 1, 0), 0, EnumFacing.NORTH, 3, 4, 5));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 3, 4, 6));
        list.add(new PlaceableDecorative(Blocks.TORCH, 3, 3, 4, 7));
        list.add(new PlaceableItemFrame(new ItemStack(Blocks.TRAPDOOR, 1, 0), 0, EnumFacing.SOUTH, 3, 4, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 4, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 4, 9));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 4, 10));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 1, 3, 4, 11));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 4, 4, 4, 1));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 4, 4, 3));
        list.add(new PlaceableDecorative(Blocks.TORCH, 4, 4, 4, 5));
        list.add(new PlaceableItemFrame(new ItemStack(Blocks.TRAPDOOR, 1, 0), 0, EnumFacing.NORTH, 4, 4, 5));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 4, 4, 6));
        list.add(new PlaceableDecorative(Blocks.TORCH, 3, 4, 4, 7));
        list.add(new PlaceableItemFrame(new ItemStack(Blocks.TRAPDOOR, 1, 0), 0, EnumFacing.SOUTH, 4, 4, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 4, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 4, 9));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 4, 10));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 4, 4, 11));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 5, 4, 0));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 5, 4, 1));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 7, 5, 4, 2));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 5, 5, 4, 3));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 6, 5, 4, 4));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 5, 4, 5));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 5, 4, 6));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 5, 4, 7));
        list.add(new PlaceableWeb(Blocks.WEB, 0, 5, 4, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 5, 4, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 5, 4, 10));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 6, 4, 0));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 6, 4, 1));
        list.add(new PlaceableBlock(Blocks.COBBLESTONE_WALL, 0, 6, 4, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 6, 4, 6));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 3, 6, 4, 8));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 2, 6, 4, 9));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 1, 5, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 1, 5, 2));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 1, 5, 3));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 1, 5, 4));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 1, 5, 5));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 3, 1, 5, 8));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 2, 1, 5, 9));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 2, 5, 0));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 2, 5, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 2, 5, 2));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 1, 2, 5, 3));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 2, 5, 4));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 2, 5, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 2, 5, 6));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 2, 5, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 2, 5, 8));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 2, 5, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 2, 5, 10));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 3, 5, 0));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 1, 3, 5, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 3, 5, 2));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 3, 5, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 3, 5, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 3, 5, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 3, 5, 6));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 7, 3, 5, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 5, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 5, 9));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 3, 5, 10));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 1, 3, 5, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 4, 5, 0));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 1, 4, 5, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 4, 5, 2));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 4, 4, 5, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 4, 4, 5, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 4, 4, 5, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 5, 6));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 7, 4, 5, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 5, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 5, 9));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 4, 5, 10));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 4, 5, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 5, 5, 0));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 5, 5, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 5, 5, 2));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 1, 5, 5, 3));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 5, 5, 4));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 5, 5, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 5, 5, 6));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 5, 5, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 5, 5, 8));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 5, 5, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 5, 5, 10));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 6, 5, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 6, 5, 2));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 6, 5, 3));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 6, 5, 4));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 6, 5, 5));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 3, 6, 5, 8));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 2, 6, 5, 9));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 1, 6, 7));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 3, 1, 6, 8));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 2, 1, 6, 9));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 1, 6, 10));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 2, 6, 6));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 2, 6, 7));
        list.add(new PlaceableWeb(Blocks.WEB, 0, 2, 6, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 2, 6, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 2, 6, 10));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 2, 6, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 3, 6, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 3, 6, 2));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 3, 6, 3));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 3, 6, 4));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 3, 6, 5));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 3, 6, 6));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 3, 3, 6, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 6, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 6, 9));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 6, 10));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 1, 3, 6, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 4, 6, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 4, 6, 2));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 4, 6, 3));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 4, 6, 4));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 4, 6, 5));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 4, 6, 6));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 3, 4, 6, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 6, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 6, 9));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 6, 10));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 0, 4, 6, 11));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 5, 6, 6));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 5, 6, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 5, 6, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 5, 6, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 5, 6, 10));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 5, 6, 11));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 6, 6, 7));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 3, 6, 6, 8));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 2, 6, 6, 9));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 6, 6, 10));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 8, 0, 7, 8));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 8, 0, 7, 9));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 8, 1, 7, 7));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 2, 1, 7, 8));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 1, 7, 9));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 8, 1, 7, 10));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 8, 2, 7, 6));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 1, 2, 7, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 2, 7, 8));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 2, 7, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 2, 7, 10));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 8, 2, 7, 11));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 8, 3, 7, 5));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 3, 7, 6));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 7, 3, 7, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 7, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 7, 9));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 3, 7, 10));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 3, 7, 11));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 8, 4, 7, 5));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 4, 7, 6));
        list.add(new PlaceableBlock(Blocks.STONE_BRICK_STAIRS, 7, 4, 7, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 7, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 7, 9));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 4, 7, 10));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 4, 7, 11));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 8, 5, 7, 6));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 5, 7, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 5, 7, 8));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 5, 7, 9));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 5, 7, 10));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 8, 5, 7, 11));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 8, 6, 7, 7));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 6, 7, 8));
        list.add(new PlaceableBlock(Blocks.STONEBRICK, 0, 6, 7, 9));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 8, 6, 7, 10));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 1, 8, 8));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 1, 8, 9));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 2, 8, 7));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 2, 8, 8));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 2, 8, 9));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 2, 8, 10));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 3, 8, 6));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 3, 8, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 8, 8));
        list.add(new PlaceableWeb(Blocks.WEB, 0, 3, 8, 9));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 3, 8, 10));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 3, 8, 11));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 4, 8, 6));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 4, 8, 7));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 8, 8));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 8, 9));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 4, 8, 10));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 4, 8, 11));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 5, 8, 7));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 5, 8, 8));
        list.add(new PlaceableBlock(Blocks.DOUBLE_STONE_SLAB, 0, 5, 8, 9));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 5, 8, 10));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 6, 8, 8));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 6, 8, 9));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 3, 9, 8));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 3, 9, 9));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 4, 9, 8));
        list.add(new PlaceableBlock(Blocks.STONE_SLAB, 0, 4, 9, 9));
        return this;
    }
}