package joshie.harvest.buildings;

import joshie.harvest.api.buildings.IBuilding;
import joshie.harvest.buildings.placeable.Placeable;
import joshie.harvest.buildings.placeable.blocks.PlaceableBlock;
import joshie.harvest.buildings.placeable.blocks.PlaceableChest;
import joshie.harvest.buildings.placeable.blocks.PlaceableDecorative;
import joshie.harvest.buildings.placeable.blocks.PlaceableFlowerPot;
import joshie.harvest.buildings.placeable.entities.PlaceableItemFrame;
import joshie.harvest.buildings.placeable.entities.PlaceableNPC;
import joshie.harvest.buildings.placeable.entities.PlaceablePainting;
import joshie.harvest.core.lib.LootStrings;
import joshie.harvest.player.town.TownData;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.math.BlockPos;

import java.util.ArrayList;

public class BuildingCarpenter extends Building {
    public BuildingCarpenter() {
        super("carpenter");
    }

    @Override
    public IBuilding addBlocks() {
        offsetY = -1;
        list = new ArrayList<Placeable>(373);
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 0, 0, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 0, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 1, 0, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 0, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 0, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 0, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 0, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 1, 0, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 0, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 2, 0, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 2, 0, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 2, 0, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 3, 0, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 3, 0, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 3, 0, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 3, 0, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 3, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 0, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 4, 0, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 4, 0, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 4, 0, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 4, 0, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 4, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 0, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 5, 0, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 5, 0, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 5, 0, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 5, 0, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 5, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 6, 0, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 6, 0, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 6, 0, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 6, 0, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 6, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 7, 0, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 0, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 0, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 0, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 0, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 7, 0, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 8, 0, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 8, 0, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 0, 0, 1, 1));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 0, 1, 2));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 0, 1, 3));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 0, 1, 4));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 0, 0, 1, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 1, 1, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 1, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 1, 1, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 1, 1, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 1, 1, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 1, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 1, 1, 6));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 12, 2, 1, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 2, 1, 1));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 2, 1, 2));
        list.add(new PlaceableDecorative(Blocks.LADDER, 5, 2, 1, 3));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 2, 1, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 2, 1, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 13, 2, 1, 6));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 12, 3, 1, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 3, 1, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 1, 3, 1, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 1, 3));
        list.add(new PlaceableItemFrame(null, 0, EnumFacing.SOUTH, 3, 1, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 3, 1, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 3, 1, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 13, 3, 1, 6));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 4, 1, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 4, 1, 1));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 9, 4, 1, 2));
        npc_offsets.put(TownData.CARPENTER_DOWNSTAIRS, new PlaceableNPC("", new BlockPos(4, 1, 3)));
        list.add(new PlaceableBlock(Blocks.CRAFTING_TABLE, 0, 4, 1, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 4, 1, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 4, 1, 6));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 12, 5, 1, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 5, 1, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 0, 5, 1, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 5, 1, 3));
        list.add(new PlaceableItemFrame(null, 0, EnumFacing.SOUTH, 5, 1, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 4, 5, 1, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 5, 1, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 13, 5, 1, 6));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 12, 6, 1, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 6, 1, 1));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 6, 1, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 6, 1, 3));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 6, 1, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 6, 1, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 13, 6, 1, 6));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 7, 1, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 1, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 7, 1, 2));
        list.add(new PlaceableDecorative(Blocks.OAK_DOOR, 0, 7, 1, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 7, 1, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 1, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 7, 1, 6));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 1, 8, 1, 1));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 15, 8, 1, 2));
        npc_offsets.put(TownData.CARPENTER_DOOR, new PlaceableNPC("", new BlockPos(8, 1, 3)));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 15, 8, 1, 4));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 1, 8, 1, 5));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 2, 1));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 2, 5));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 1, 2, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 2, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 0, 1, 2, 2));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 0, 1, 2, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 0, 1, 2, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 2, 5));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 1, 2, 6));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 2, 2, 1));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 2, 2, 2));
        list.add(new PlaceableDecorative(Blocks.LADDER, 5, 2, 2, 3));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 2, 2, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 2, 2, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 3, 2, 1));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 3, 2, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 2, 3));
        list.add(new PlaceableFlowerPot(Blocks.FLOWER_POT, 5, 3, 2, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 3, 2, 5));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 4, 2, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 4, 2, 1));
        list.add(new PlaceableDecorative(Blocks.TORCH, 3, 4, 2, 2));
        list.add(new PlaceableItemFrame(new ItemStack(Blocks.TRAPDOOR, 1, 0), 0, EnumFacing.SOUTH, 4, 2, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 2, 3));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 2, 4));
        list.add(new PlaceableItemFrame(new ItemStack(Items.STONE_AXE, 1, 0), 0, EnumFacing.NORTH, 4, 2, 4, LootStrings.CARPENTER_FRAME));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 4, 2, 5));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 4, 2, 6));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 5, 2, 1));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 5, 2, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 5, 2, 3));
        list.add(new PlaceableDecorative(Blocks.LEVER, 13, 5, 2, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 5, 2, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 6, 2, 1));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 6, 2, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 6, 2, 3));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 6, 2, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 6, 2, 5));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 7, 2, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 2, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 1, 7, 2, 2));
        list.add(new PlaceableDecorative(Blocks.OAK_DOOR, 8, 7, 2, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 1, 7, 2, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 2, 5));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 7, 2, 6));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 2, 1));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 8, 2, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 8, 2, 3));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 8, 2, 4));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 2, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 4, 0, 3, 1));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 3, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 4, 0, 3, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 6, 1, 3, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 3, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 4, 1, 3, 2));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 1, 3, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 4, 1, 3, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 3, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 7, 1, 3, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 2, 3, 0));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 2, 3, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 3, 2));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 2, 2, 3, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 3, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 2, 3, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 2, 3, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 3, 3, 0));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 3, 3, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 3, 3, 2));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 3, 3, 3));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 3, 3, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 3, 3, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 3, 3, 6));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 6, 4, 3, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 4, 3, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 4, 3, 2));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 4, 3, 3));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 4, 3, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 4, 3, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 7, 4, 3, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 5, 3, 0));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 5, 3, 1));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 1, 5, 3, 2));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 5, 3, 3));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 1, 5, 3, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 5, 3, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 5, 3, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 6, 3, 0));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 6, 3, 1));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 1, 6, 3, 2));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 1, 6, 3, 3));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 1, 6, 3, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 6, 3, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 6, 3, 6));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 6, 7, 3, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 3, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 7, 3, 2));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 7, 3, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 7, 3, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 3, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 7, 7, 3, 6));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 5, 8, 3, 1));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 8, 3, 2));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 3, 3));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 8, 3, 4));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 5, 8, 3, 5));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 0, 4, 1));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 4, 2));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 4, 4));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 0, 4, 5));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 1, 4, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 1, 4, 1));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 1, 4, 2));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 1, 4, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 1, 4, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 1, 4, 5));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 1, 4, 6));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 12, 2, 4, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 5, 2, 4, 1));
        list.add(new PlaceableChest(Blocks.CHEST, 5, 2, 4, 2, LootStrings.JADE_CHEST));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 2, 4, 3));
        list.add(new PlaceableChest(Blocks.CHEST, 5, 2, 4, 4, LootStrings.YULIF_CHEST));
        list.add(new PlaceableBlock(Blocks.LOG, 5, 2, 4, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 13, 2, 4, 6));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 12, 3, 4, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 5, 3, 4, 1));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 3, 4, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 4, 3));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 3, 4, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 5, 3, 4, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 13, 3, 4, 6));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 4, 4, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 4, 4, 1));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 5, 4, 4, 2));
        list.add(new PlaceableNPC("jade", new BlockPos(4, 4, 3)));
        npc_offsets.put(TownData.JADE, new PlaceableNPC("", new BlockPos(4, 4, 3)));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 4, 4, 4, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 4, 4, 5));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 4, 4, 6));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 12, 5, 4, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 5, 5, 4, 1));
        list.add(new PlaceableBlock(Blocks.CARPET, 5, 5, 4, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 5, 4, 3));
        list.add(new PlaceableBlock(Blocks.CARPET, 4, 5, 4, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 5, 5, 4, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 13, 5, 4, 6));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 4, 6, 4, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 5, 6, 4, 1));
        list.add(new PlaceableBlock(Blocks.CARPET, 0, 6, 4, 2));
        list.add(new PlaceableFlowerPot(Blocks.FLOWER_POT, 5, 6, 4, 3));
        list.add(new PlaceableBlock(Blocks.CARPET, 0, 6, 4, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 5, 6, 4, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 13, 6, 4, 6));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 7, 4, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 7, 4, 1));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 7, 4, 2));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 7, 4, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 7, 4, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 7, 4, 5));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 7, 4, 6));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 8, 4, 1));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 4, 2));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 4, 4));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 8, 4, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 0, 5, 1));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 7, 0, 5, 2));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 5, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 6, 0, 5, 4));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 0, 5, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 1, 5, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 1, 5, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 1, 5, 2));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 1, 5, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 1, 5, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 1, 5, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 1, 5, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 2, 5, 0));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 2, 5, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 2, 5, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 2, 5, 3));
        list.add(new PlaceablePainting("Wasteland", EnumFacing.EAST, 2, 5, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 2, 5, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 2, 5, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 2, 5, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 3, 5, 0));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 3, 5, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 3, 5, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 5, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 3, 5, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 3, 5, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 3, 5, 6));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 4, 5, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 5, 1));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 4, 5, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 5, 3));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 4, 5, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 5, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 4, 5, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 5, 5, 0));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 5, 5, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 5, 5, 2));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 5, 5, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 5, 5, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 5, 5, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 5, 5, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 6, 5, 0));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 6, 5, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 6, 5, 2));
        list.add(new PlaceableDecorative(Blocks.TORCH, 2, 6, 5, 3));
        list.add(new PlaceableItemFrame(new ItemStack(Blocks.TRAPDOOR, 1, 0), 0, EnumFacing.WEST, 6, 5, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 6, 5, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 6, 5, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 6, 5, 6));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 7, 5, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 7, 5, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 7, 5, 2));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 7, 5, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 7, 5, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 7, 5, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 7, 5, 6));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 8, 5, 1));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 7, 8, 5, 2));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 5, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 6, 8, 5, 4));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 8, 5, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 0, 6, 2));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 5, 0, 6, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 0, 6, 4));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 1, 6, 1));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 7, 1, 6, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 1, 6, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 6, 1, 6, 4));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 1, 6, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 2, 6, 2));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 1, 2, 6, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 2, 6, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 3, 6, 2));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 1, 3, 6, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 3, 6, 4));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 4, 6, 1));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 7, 4, 6, 2));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 4, 6, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 6, 4, 6, 4));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 4, 6, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 5, 6, 2));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 1, 5, 6, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 5, 6, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 6, 6, 2));
        list.add(new PlaceableBlock(Blocks.DOUBLE_WOODEN_SLAB, 1, 6, 6, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 6, 6, 4));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 7, 6, 1));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 7, 7, 6, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 3, 7, 6, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 6, 7, 6, 4));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 7, 6, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 8, 6, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 8, 6, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 8, 6, 4));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 0, 7, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 1, 7, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 1, 7, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 1, 7, 4));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 2, 7, 3));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 3, 7, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 4, 7, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 7, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 4, 7, 4));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 5, 7, 3));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 6, 7, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 7, 7, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 7, 7, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 7, 7, 4));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 8, 7, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 1, 1, 8, 3));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 4, 8, 3));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 0, 7, 8, 3));
        return this;
    }
}