package joshie.harvest.buildings;

import joshie.harvest.api.buildings.IBuilding;
import joshie.harvest.buildings.loader.HFBuildings;
import joshie.harvest.buildings.placeable.Placeable;
import joshie.harvest.buildings.placeable.blocks.PlaceableBlock;
import joshie.harvest.buildings.placeable.blocks.PlaceableDecorative;
import joshie.harvest.buildings.placeable.blocks.PlaceableFlowerPot;
import joshie.harvest.buildings.placeable.blocks.PlaceableWeb;
import joshie.harvest.buildings.placeable.entities.PlaceableItemFrame;
import joshie.harvest.buildings.placeable.entities.PlaceableNPC;
import joshie.harvest.core.handlers.HFTrackers;
import joshie.harvest.core.lib.LootStrings;
import joshie.harvest.player.town.TownData;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumFacing;
import net.minecraft.world.World;

import java.util.List;

public class BuildingBarn extends BuildingAbstract {
    public BuildingBarn() {
        super("barn");
    }

    @Override
    public int getOffsetY() {
        return -1;
    }

    @Override
    public long getCost() {
        return 3000L;
    }

    @Override
    public int getWoodCount() {
        return 160;
    }

    @Override
    public int getStoneCount() {
        return 0;
    }

    @Override
    public boolean canBuy(World world, EntityPlayer player) {
        return HFTrackers.getPlayerTracker(player).getTown().hasBuilding(HFBuildings.blacksmith);
    }

    @Override
    public String[] getRequirements() {
        return new String[] { "blacksmith" };
    }

    @Override
    public IBuilding addBlocks(List<Placeable> list) {
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 0, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 0, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 0, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 0, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 0, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 0, 7));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 0, 8));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 0, 9));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 0, 10));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 0, 11));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 0, 1));
        list.add(new PlaceableBlock(Blocks.DIRT, 0, 2, 0, 2));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 2, 0, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 2, 0, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 0, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 0, 7));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 2, 0, 8));
        list.add(new PlaceableBlock(Blocks.DIRT, 0, 2, 0, 9));
        list.add(new PlaceableBlock(Blocks.DIRT, 0, 2, 0, 10));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 0, 11));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 3, 0, 1));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 3, 0, 2));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 3, 0, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 3, 0, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 3, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 3, 0, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 3, 0, 7));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 3, 0, 8));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 3, 0, 9));
        list.add(new PlaceableBlock(Blocks.DIRT, 0, 3, 0, 10));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 3, 0, 11));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 4, 0, 1));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 4, 0, 2));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 4, 0, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 0, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 4, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 0, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 4, 0, 7));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 4, 0, 8));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 4, 0, 9));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 4, 0, 10));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 4, 0, 11));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 5, 0, 1));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 5, 0, 2));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 5, 0, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 5, 0, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 5, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 5, 0, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 5, 0, 7));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 5, 0, 8));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 5, 0, 9));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 5, 0, 10));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 5, 0, 11));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 6, 0, 1));
        list.add(new PlaceableBlock(Blocks.DIRT, 0, 6, 0, 2));
        list.add(new PlaceableBlock(Blocks.DIRT, 0, 6, 0, 3));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 6, 0, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 6, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 6, 0, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 6, 0, 7));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 6, 0, 8));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 6, 0, 9));
        list.add(new PlaceableBlock(Blocks.DIRT, 1, 6, 0, 10));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 6, 0, 11));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 0, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 0, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 0, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 0, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 7, 0, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 7, 0, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 5, 7, 0, 7));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 0, 8));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 0, 9));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 0, 10));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 0, 11));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 1, 1));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 0, 1, 2));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 0, 1, 3));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 0, 1, 4));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 0, 1, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 0, 1, 6));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 0, 1, 7));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 0, 1, 8));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 0, 1, 9));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 0, 1, 10));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 1, 11));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 1, 1, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 1, 1));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 1, 1, 2));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 1, 1, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 1, 4));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 1, 1, 5));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 1, 1, 6));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 1, 1, 7));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 1, 8));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 1, 1, 9));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 1, 1, 10));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 1, 11));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 1, 1, 12));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 12, 2, 1, 0));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 2, 1, 1));
        list.add(new PlaceableBlock(Blocks.HAY_BLOCK, 0, 2, 1, 2));
        list.add(new PlaceableDecorative(Blocks.RED_FLOWER, 4, 2, 1, 3));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 2, 1, 4));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 15, 2, 1, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 15, 2, 1, 6));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 15, 2, 1, 7));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 2, 1, 8));
        list.add(new PlaceableBlock(Blocks.HAY_BLOCK, 0, 2, 1, 9));
        list.add(new PlaceableBlock(Blocks.HAY_BLOCK, 0, 2, 1, 10));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 2, 1, 11));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 13, 2, 1, 12));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 12, 3, 1, 0));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 3, 1, 1));
        list.add(new PlaceableDecorative(Blocks.RED_MUSHROOM, 0, 3, 1, 2));
        list.add(new PlaceableDecorative(Blocks.RED_MUSHROOM, 0, 3, 1, 3));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 3, 1, 4));
        list.add(new PlaceableNPC(TownData.JIM, "jim", 3, 1, 6));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 3, 1, 6));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 3, 1, 8));
        list.add(new PlaceableBlock(Blocks.HAY_BLOCK, 0, 3, 1, 10));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 3, 1, 11));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 13, 3, 1, 12));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 12, 4, 1, 0));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 4, 1, 1));
        list.add(new PlaceableBlock(Blocks.TALLGRASS, 2, 4, 1, 2));
        list.add(new PlaceableDecorative(Blocks.BROWN_MUSHROOM, 0, 4, 1, 3));
        list.add(new PlaceableDecorative(Blocks.OAK_FENCE_GATE, 2, 4, 1, 4));
        list.add(new PlaceableDecorative(Blocks.OAK_FENCE_GATE, 0, 4, 1, 8));
        list.add(new PlaceableDecorative(Blocks.RED_FLOWER, 2, 4, 1, 10));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 4, 1, 11));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 13, 4, 1, 12));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 12, 5, 1, 0));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 5, 1, 1));
        list.add(new PlaceableDecorative(Blocks.BROWN_MUSHROOM, 0, 5, 1, 2));
        list.add(new PlaceableDecorative(Blocks.BROWN_MUSHROOM, 0, 5, 1, 3));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 5, 1, 4));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 5, 1, 8));
        list.add(new PlaceableDecorative(Blocks.YELLOW_FLOWER, 0, 5, 1, 10));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 5, 1, 11));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 13, 5, 1, 12));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 12, 6, 1, 0));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 6, 1, 1));
        list.add(new PlaceableBlock(Blocks.HAY_BLOCK, 8, 6, 1, 2));
        list.add(new PlaceableBlock(Blocks.HAY_BLOCK, 8, 6, 1, 3));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 6, 1, 4));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 6, 1, 8));
        list.add(new PlaceableBlock(Blocks.TALLGRASS, 1, 6, 1, 9));
        list.add(new PlaceableBlock(Blocks.CAULDRON, 3, 6, 1, 10));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 6, 1, 11));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 13, 6, 1, 12));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 7, 1, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 1, 1));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 7, 1, 2));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 7, 1, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 1, 4));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 7, 1, 5));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 7, 1, 6));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 7, 1, 7));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 1, 8));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 7, 1, 9));
        list.add(new PlaceableBlock(Blocks.STAINED_HARDENED_CLAY, 12, 7, 1, 10));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 1, 11));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 7, 1, 12));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 1, 1));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 15, 8, 1, 2));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 15, 8, 1, 3));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 8, 1, 4));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 8, 1, 8));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 15, 8, 1, 9));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 15, 8, 1, 10));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 1, 11));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 2, 3));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 0, 2, 4));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 0, 2, 8));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 2, 9));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 2, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 2, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 2, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 2, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 1, 2, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 1, 1, 2, 6));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 1, 2, 7));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 2, 8));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 2, 9));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 2, 10));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 2, 11));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 2, 2, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 2, 1));
        list.add(new PlaceableDecorative(Blocks.RED_MUSHROOM, 0, 2, 2, 2));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 2, 2, 3));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 3, 2, 2, 4));
        list.add(new PlaceableDecorative(Blocks.VINE, 2, 2, 2, 5));
        list.add(new PlaceableDecorative(Blocks.VINE, 2, 2, 2, 7));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 3, 2, 2, 8));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 2, 2, 9));
        list.add(new PlaceableBlock(Blocks.HAY_BLOCK, 0, 2, 2, 10));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 2, 11));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 2, 2, 12));
        list.add(new PlaceableBlock(Blocks.STAINED_GLASS_PANE, 14, 3, 2, 1));
        list.add(new PlaceableDecorative(Blocks.VINE, 4, 3, 2, 2));
        list.add(new PlaceableDecorative(Blocks.VINE, 2, 3, 2, 10));
        list.add(new PlaceableBlock(Blocks.STAINED_GLASS_PANE, 14, 3, 2, 11));
        list.add(new PlaceableBlock(Blocks.STAINED_GLASS_PANE, 14, 4, 2, 1));
        list.add(new PlaceableDecorative(Blocks.VINE, 4, 4, 2, 2));
        list.add(new PlaceableBlock(Blocks.STAINED_GLASS_PANE, 14, 4, 2, 11));
        list.add(new PlaceableBlock(Blocks.STAINED_GLASS_PANE, 14, 5, 2, 1));
        list.add(new PlaceableDecorative(Blocks.VINE, 1, 5, 2, 10));
        list.add(new PlaceableBlock(Blocks.STAINED_GLASS_PANE, 14, 5, 2, 11));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 6, 2, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 6, 2, 1));
        list.add(new PlaceableBlock(Blocks.HAY_BLOCK, 8, 6, 2, 2));
        list.add(new PlaceableBlock(Blocks.HAY_BLOCK, 8, 6, 2, 3));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 2, 6, 2, 4));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 2, 6, 2, 8));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 6, 2, 9));
        list.add(new PlaceableDecorative(Blocks.VINE, 1, 6, 2, 10));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 6, 2, 11));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 6, 2, 12));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 2, 1));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 2, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 2, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 2, 4));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 7, 2, 5));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 7, 2, 6));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 7, 2, 7));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 2, 8));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 2, 9));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 2, 10));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 2, 11));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 2, 3));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 8, 2, 4));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 8, 2, 8));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 2, 9));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 0, 3, 0));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 3, 1));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 0, 3, 4));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 3, 6));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 0, 3, 8));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 3, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 0, 3, 12));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 1, 3, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 3, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 1, 1, 3, 2));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 1, 1, 3, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 3, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 1, 3, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 1, 3, 6));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 1, 3, 7));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 3, 8));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 1, 1, 3, 9));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 1, 1, 3, 10));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 3, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 1, 3, 12));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 2, 3, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 3, 1));
        list.add(new PlaceableDecorative(Blocks.VINE, 4, 2, 3, 2));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 2, 3, 4));
        list.add(new PlaceableDecorative(Blocks.VINE, 2, 2, 3, 5));
        list.add(new PlaceableDecorative(Blocks.VINE, 2, 2, 3, 7));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 2, 3, 8));
        list.add(new PlaceableFlowerPot(Blocks.FLOWER_POT, 4, 2, 3, 10));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 3, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 2, 3, 12));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 3, 3, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 3, 3, 1));
        list.add(new PlaceableDecorative(Blocks.VINE, 4, 3, 3, 2));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 3, 3, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 3, 3, 12));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 4, 3, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 4, 3, 1));
        list.add(new PlaceableDecorative(Blocks.VINE, 4, 4, 3, 2));
        list.add(new PlaceableItemFrame(new ItemStack(Items.LEAD, 1, 0), 0, EnumFacing.SOUTH, 4, 3, 2, LootStrings.BARN_FRAME));
        list.add(new PlaceableBlock(Blocks.AIR, 0, 4, 3, 10));
        list.add(new PlaceableItemFrame(new ItemStack(Items.LEAD, 1, 0), 0, EnumFacing.NORTH, 4, 3, 10, LootStrings.BARN_FRAME));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 4, 3, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 4, 3, 12));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 5, 3, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 5, 3, 1));
        list.add(new PlaceableDecorative(Blocks.VINE, 1, 5, 3, 10));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 5, 3, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 5, 3, 12));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 6, 3, 0));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 6, 3, 1));
        list.add(new PlaceableWeb(Blocks.WEB, 0, 6, 3, 2));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 6, 3, 4));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 6, 3, 8));
        list.add(new PlaceableDecorative(Blocks.VINE, 1, 6, 3, 10));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 6, 3, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 6, 3, 12));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 7, 3, 0));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 3, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 0, 7, 3, 2));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 0, 7, 3, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 3, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 7, 3, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 7, 3, 6));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 7, 3, 7));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 3, 8));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 0, 7, 3, 9));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 0, 7, 3, 10));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 3, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 7, 3, 12));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 8, 3, 0));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 3, 1));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 8, 3, 4));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 8, 3, 8));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 3, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 8, 3, 12));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 0, 4, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 0, 4, 2));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 0, 4, 4));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 0, 4, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 0, 4, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 0, 4, 7));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 0, 4, 8));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 0, 4, 10));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 0, 4, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 1, 4, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 1, 4, 2));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 1, 4, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 4, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 1, 4, 5));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 1, 4, 6));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 1, 4, 7));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 4, 8));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 1, 4, 9));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 5, 1, 4, 10));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 1, 4, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 2, 4, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 2, 4, 2));
        list.add(new PlaceableDecorative(Blocks.TORCH, 1, 2, 4, 4));
        list.add(new PlaceableItemFrame(new ItemStack(Blocks.TRAPDOOR, 1, 0), 0, EnumFacing.EAST, 2, 4, 4));
        list.add(new PlaceableDecorative(Blocks.VINE, 2, 2, 4, 5));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 2, 4, 6));
        list.add(new PlaceableDecorative(Blocks.VINE, 2, 2, 4, 7));
        list.add(new PlaceableDecorative(Blocks.TORCH, 1, 2, 4, 8));
        list.add(new PlaceableItemFrame(new ItemStack(Blocks.TRAPDOOR, 1, 0), 0, EnumFacing.EAST, 2, 4, 8));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 2, 4, 10));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 2, 4, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 3, 4, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 3, 4, 2));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 3, 4, 10));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 3, 4, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 4, 4, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 4, 4, 2));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 4, 4, 10));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 4, 4, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 5, 4, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 5, 4, 2));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 5, 4, 10));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 5, 4, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 6, 4, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 6, 4, 2));
        list.add(new PlaceableDecorative(Blocks.TORCH, 2, 6, 4, 4));
        list.add(new PlaceableItemFrame(new ItemStack(Blocks.TRAPDOOR, 1, 0), 0, EnumFacing.WEST, 6, 4, 4));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 6, 4, 6));
        list.add(new PlaceableDecorative(Blocks.TORCH, 2, 6, 4, 8));
        list.add(new PlaceableItemFrame(new ItemStack(Blocks.TRAPDOOR, 1, 0), 0, EnumFacing.WEST, 6, 4, 8));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 9, 6, 4, 10));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 6, 4, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 7, 4, 1));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 4, 7, 4, 2));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 4, 7, 4, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 4, 4));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 7, 4, 5));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 7, 4, 6));
        list.add(new PlaceableBlock(Blocks.LOG, 9, 7, 4, 7));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 4, 8));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 4, 7, 4, 9));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 4, 7, 4, 10));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 7, 4, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 8, 4, 1));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 8, 4, 2));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 8, 4, 4));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 8, 4, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 8, 4, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 8, 4, 7));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 8, 4, 8));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 8, 4, 10));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 8, 4, 11));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 0, 5, 3));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 5, 4));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 0, 5, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 14, 0, 5, 7));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 5, 8));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 0, 5, 9));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 1, 5, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 5, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 5, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 5, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 5, 7));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 1, 5, 8));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 1, 5, 9));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 2, 5, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 2, 5, 4));
        list.add(new PlaceableDecorative(Blocks.VINE, 2, 2, 5, 5));
        list.add(new PlaceableDecorative(Blocks.VINE, 2, 2, 5, 6));
        list.add(new PlaceableDecorative(Blocks.VINE, 2, 2, 5, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 2, 5, 8));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 2, 5, 9));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 3, 5, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 3, 5, 4));
        list.add(new PlaceableWeb(Blocks.WEB, 0, 3, 5, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 3, 5, 8));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 3, 5, 9));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 4, 5, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 4, 5, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 4, 5, 8));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 4, 5, 9));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 5, 5, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 5, 5, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 5, 5, 8));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 5, 5, 9));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 6, 5, 3));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 6, 5, 4));
        list.add(new PlaceableWeb(Blocks.WEB, 0, 6, 5, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 6, 5, 8));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 6, 5, 9));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 7, 5, 3));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 5, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 5, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 5, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 5, 7));
        list.add(new PlaceableBlock(Blocks.LOG, 1, 7, 5, 8));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 7, 5, 9));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 8, 5, 3));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 5, 4));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 15, 8, 5, 5));
        list.add(new PlaceableDecorative(Blocks.TRAPDOOR, 15, 8, 5, 7));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 5, 8));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 5, 8, 5, 9));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 0, 6, 4));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 6, 5));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 2, 0, 6, 7));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 0, 6, 8));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 1, 6, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 6, 5));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 1, 6, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 6, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 1, 6, 8));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 2, 6, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 2, 6, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 2, 6, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 2, 6, 8));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 3, 6, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 3, 6, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 3, 6, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 3, 6, 8));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 4, 6, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 4, 6, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 4, 6, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 4, 6, 8));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 5, 6, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 5, 6, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 5, 6, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 5, 6, 8));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 6, 6, 4));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 7, 6, 6, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 6, 6, 6, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 6, 6, 8));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 7, 6, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 6, 5));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 7, 6, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 6, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 7, 6, 8));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 8, 6, 4));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 6, 5));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 1, 8, 6, 7));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 8, 6, 8));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 7, 0, 7, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 6, 0, 7, 7));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 1, 7, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 7, 5));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 1, 7, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 7, 7));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 1, 7, 8));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 2, 7, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 2, 7, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 3, 7, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 3, 7, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 4, 7, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 4, 7, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 5, 7, 5));
        list.add(new PlaceableWeb(Blocks.WEB, 0, 5, 7, 6));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 5, 7, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 6, 7, 5));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 6, 7, 7));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 4, 7, 7, 4));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 7, 5));
        list.add(new PlaceableBlock(Blocks.OAK_FENCE, 0, 7, 7, 6));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 7, 7));
        list.add(new PlaceableDecorative(Blocks.WOODEN_BUTTON, 3, 7, 7, 8));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 7, 8, 7, 5));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 6, 8, 7, 7));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 0, 8, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 0, 8, 6));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 0, 8, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 1, 8, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 1, 8, 6));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 1, 8, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 2, 8, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 2, 8, 6));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 2, 8, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 3, 8, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 3, 8, 6));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 3, 8, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 4, 8, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 4, 8, 6));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 4, 8, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 5, 8, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 5, 8, 6));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 5, 8, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 6, 8, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 6, 8, 6));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 6, 8, 7));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 2, 7, 8, 5));
        list.add(new PlaceableBlock(Blocks.PLANKS, 1, 7, 8, 6));
        list.add(new PlaceableBlock(Blocks.SPRUCE_STAIRS, 3, 7, 8, 7));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 2, 8, 8, 5));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 13, 8, 8, 6));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 3, 8, 8, 7));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 1, 0, 9, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 1, 9, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 2, 9, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 3, 9, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 4, 9, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 5, 9, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 6, 9, 6));
        list.add(new PlaceableBlock(Blocks.WOODEN_SLAB, 1, 7, 9, 6));
        list.add(new PlaceableBlock(Blocks.DARK_OAK_STAIRS, 0, 8, 9, 6));
        return this;
    }
}